/* ============================================================================
   FILE: npc_system.js — "Surviving Adamsville" pedestrian system (~1,000 NPCs)
   ----------------------------------------------------------------------------
   PURPOSE: Free-thinking pedestrian population streaming around the player.
   KEY SYSTEMS:
     - Population: NPC_COUNT=1000 plain data objects (positions only) — no
       geometry unless near the player. Placement is DETERMINISTIC (seeded
       mulberry32, seed 19951013): stable spawns across loads. AI uses
       Math.random (non-deterministic behavior).
     - Free-think AI: no waypoints, no pathfinding — WALK a heading for a few
       seconds, IDLE (look around), TURN to a new heading; a 3.2u lookahead
       probe turns the NPC away from blockages. Simple sim, Joshua's rule.
     - Streaming renderer: only MAX_VISIBLE=40 bodies within 150u of the
       camera get instanced bodies (hysteresis: released beyond 200u), 6
       InstancedMeshes (torso/head/2 arms/2 legs), per-instance colors
       (skin head+arms = short-sleeve look, shirt torso, pants legs).
       Limb animation only within 80u (LOD); distant bodies are static.
       TCL T513V (Joshua's phone) budget drove these caps.
     - Border containment: BORDER convex quad → inward half-planes, 10u inner
       margin; NPCs turn around at the world edge instead of walking out.
     - NPC QA testers: every NPC files "glitch dispatch calls" into the
       Report when stuck >5s, blocked >10 failed turns, or in deep water —
       Joshua's live audit of broken geometry.
   JOSHUA SPECS ENCODED:
     - NPC population ~1,000: adult men (~45%), adult women (~40%), and a
       smaller number of 16-year-old boys (~15%). NOBODY under 16, NOBODY
       over 65 — hard rule, encoded in TYPE_NAMES and the age-16 boy model
       (0.85 scale). No children, no elderly.
     - Pedestrians never spawn on highways (I-20/85/75/285).
     - Spawn mix: 55% roadside (off the asphalt: half-width + 2.5-5.5u),
       20% commercial, 25% residential.
     - LIFE SIM (queued, not yet in this file): each NPC can have a home
       residence, a car, and a workplace — unassigned shows "unspecified";
       Joshua assigns homes from a dropdown of houses/apartments. Building
       entry is fade/morph-through-the-door (no door animation) — NPC
       disappears inside a while, reappears when leaving.
   ============================================================================ */
/* ============================================================================
   NPC PEDESTRIAN SYSTEM — "Surviving Adamsville" v1.9
   ~1,000 free-think pedestrians. Each NPC is DATA ONLY when distant
   (no geometry, no Three.js objects). Bodies stream in as instanced boxes
   only near the camera. Every NPC is also a QA tester: when one hits a
   problem it files a glitch dispatch call into the Report.

   ---- INTEGRATION (build agent: 2 steps, do NOT edit this file) ----
   1. In index.html, AFTER the main inline <script>...</script> block
      (right before </body>), add:
          <script src="npc_system.js"></script>
      (Must load after the main script: it needs roadDrawData, PLACED_HOUSES,
      bldgGrid, BORDER, heightAt(), onRoad(), inWater(), waterDepthAt(),
      Report, THREE and scene to exist.)
   2. In animate(), after updateCamera(dt); add:
          try{ updateNPCs(dt, player.mesh.position); }catch(e){}

   Reads (all optional/guarded — the system degrades gracefully if one is
   missing): player, car, roadDrawData, PLACED_HOUSES, OSM_BUILDINGS,
   bldgGrid, BORDER, heightAt, onRoad, inWater, waterDepthAt, Report.
   Writes: 6 InstancedMeshes added to scene; window.updateNPCs;
   Report.setSys('npc', ...) every 5s.
   ============================================================================ */
(function npcPedestrians(){
'use strict';

/* ---------------- config ---------------- */
var NPC_COUNT   = 1000;   // Joshua's spec: ~1,000 pedestrians
var MAX_VISIBLE = 40;     // hard cap on instanced bodies (TCL T513V budget)
var VISIBLE_R   = 150;    // stream a body in within this distance (u)
var HIDE_R      = 200;    // release the body beyond this distance (hysteresis)
var ANIM_R      = 80;     // limb animation only inside this range (LOD)
var ST_WALK = 0, ST_IDLE = 1, ST_TURN = 2;
var STATE_NAMES = ['WALK','IDLE','TURN'];
var TYPE_NAMES  = ['man','woman','boy16'];   // nobody under 16, nobody over 65

/* 1995-Atlanta palettes. Skin: range of brown tones (per spec). */
var SKINS  = [0x4a2f1c,0x5a3a24,0x6b4429,0x7d5230,0x8a5f36,0x93683c,0xa07a48];
var SHIRTS = [0xc23b2e,0x2e5fa3,0x2e8b57,0xe0e0e0,0xe8b923,0x1f8a8a,0xd96c2c,
              0x7b4fa3,0x555c66,0x222226,0xb03060,0x3a7d44,0xc7c7c7,0x8a2be2];
var PANTS  = [0x2e4a6b,0x1f2a3a,0x141414,0x9a8a6a,0x5a4632,0x666c75,0x3b3f4a];

/* ---------------- state ---------------- */
var npcs=[];            // the population: plain data objects, nothing else
var slots=[];           // MAX_VISIBLE entries: npc ref or null
var glitchLog=[];       // newest 50 dispatch calls
var glitchTotal=0;
var npcReady=false, npcTick=0, visCount=0;
var streamT=0, repT=0;

/* scratch / temps — allocated once, never in the hot loop */
var _m1=null,_m2=null,_m3=null,_m4=null,_m5=null,_m6=null,_m7=null,_out=null;
var _col=null, _free=[], _mesh=null;   // _mesh: {torso,head,armL,armR,legL,legR}
var walkRoads=[], comSpots=[], resSpots=[];
var borderOK=null;      // null = no constraint; else {px,py...} half-planes

/* Deterministic RNG for PLACEMENT ONLY (stable spawns). AI uses Math.random. */
function mulberry32(a){
  return function(){
    a|=0; a=a+0x6D2B79F5|0;
    var t=Math.imul(a^a>>>15,1|a);
    t=t+Math.imul(t^t>>>7,61|t)^t;
    return ((t^t>>>14)>>>0)/4294967296;
  };
}
var srand=mulberry32(19951013);

/* ---------------- border containment ----------------
   BORDER is a convex quad [{x,z}x4]. Precompute inward half-planes so NPCs
   TURN around instead of wandering out of the world. 10u inner margin. */
/* buildBorder() — precomputes the BORDER polygon's inward-facing half-planes
   (one per edge) so insideBorder() can cheaply test containment. BORDER is a
   convex quad; edge direction follows the polygon's winding (s=+1/-1). */
function buildBorder(){
  try{
    if (typeof BORDER==='undefined'||!BORDER||BORDER.length<3){ borderOK=null; return; }
    var n=BORDER.length, i, area=0;
    for (i=0;i<n;i++){ var a=BORDER[i], b=BORDER[(i+1)%n]; area+=a.x*b.z-b.x*a.z; }
    var s=area>0?1:-1, E=[];
    for (i=0;i<n;i++){
      var p=BORDER[i], q=BORDER[(i+1)%n];
      var ex=q.x-p.x, ez=q.z-p.z, L=Math.hypot(ex,ez)||1;
      E.push({px:p.x,pz:p.z,ex:ex/L,ez:ez/L,s:s});
    }
    borderOK=E;
  }catch(e){ borderOK=null; }
}
/* insideBorder(x,z) — true when (x,z) is at least 10u inside every border
   edge. The 10u margin keeps NPCs off the world wall. Returns true when no
   border constraint exists. */
function insideBorder(x,z){
  if (!borderOK) return true;
  for (var i=0;i<borderOK.length;i++){
    var e=borderOK[i];
    var cr=e.ex*(z-e.pz)-e.ez*(x-e.px);   // cross(edge, point-p)
    if (e.s*cr < 10) return false;        // 10u margin inside the wall
  }
  return true;
}

/* ---------------- blockage probe ----------------
   Cheap "can I step here?" test: water, road corridor, OSM building
   colliders (spatial grid, cell 40u — same grid the game uses), ranch
   houses (PLACED_HOUSES is small, direct loop). Trees/furniture are
   intentionally ignored: walking past a trunk is invisible at this scale. */
/* npcBlocked(x,z) — cheap "can I step here?" probe. Returns true for water,
   road corridors, border edges, OSM building colliders (40u spatial grid —
   the same grid the game uses), and ranch houses (small list, direct loop).
   Trees/furniture are INTENTIONALLY ignored: walking past a trunk is
   invisible at this scale, and checking them would cost far more than it
   saves. All wrapped — a missing world feature degrades to "not blocked". */
function npcBlocked(x,z){
  try{
    if (typeof inWater==='function' && inWater(x,z)) return true;
    if (typeof onRoad==='function' && onRoad(x,z)) return true;
    if (!insideBorder(x,z)) return true;
    if (typeof bldgGrid!=='undefined' && bldgGrid){
      var cx=Math.floor(x/40), cz=Math.floor(z/40);
      for (var gx=cx-1;gx<=cx+1;gx++) for (var gz=cz-1;gz<=cz+1;gz++){
        var cell=bldgGrid[gx+','+gz]; if(!cell) continue;
        for (var i=0;i<cell.length;i++){
          var c=cell[i], dx=x-c.x, dz=z-c.z, rr=c.r+0.7;
          if (dx*dx+dz*dz < rr*rr) return true;
        }
      }
    }
    if (typeof PLACED_HOUSES!=='undefined' && PLACED_HOUSES){
      for (var j=0;j<PLACED_HOUSES.length;j++){
        var h=PLACED_HOUSES[j];
        var hx=x-h[0], hz=z-h[1], hr=Math.max(h[2],h[3])/2+1.7;
        if (hx*hx+hz*hz < hr*hr) return true;
      }
    }
  }catch(e){}
  return false;
}

/* ---------------- glitch dispatch ----------------
   Every NPC is a QA tester. problem = what went wrong; what = what it was
   doing (state); why = its intent. Newest 50 kept. */
/* npcGlitch(n, problem, what, why) — files one NPC QA dispatch call: who
   (NPC#id + type), where (rounded x,z), what they were doing (state), why
   (intent), and what went wrong. Keeps the newest 50; forces the next report
   tick (repT=0) so the Report panel shows it promptly. Joshua reads these
   as his live geometry audit. */
function npcGlitch(n, problem, what, why){
  glitchTotal++;
  try{
    glitchLog.push({
      caller: 'NPC#'+n.id+' ('+TYPE_NAMES[n.type]+')',
      location: [+n.x.toFixed(1), +n.z.toFixed(1)],
      what: what || STATE_NAMES[n.state],
      why: why || 'deciding where to go',
      problem: problem,
      t: new Date().toISOString()
    });
    if (glitchLog.length>50) glitchLog.splice(0, glitchLog.length-50);
    repT=0;   // publish on the next frame
  }catch(e){}
}

/* ---------------- spawn placement (deterministic) ---------------- */
/* collectSpots() — builds the three spawn pools once: walkRoads (non-highway
   roads only — nobody spawns on I-20/85/75/285), comSpots (OSM type 1/2 =
   commercial/apartment), resSpots (PLACED_HOUSES). Called once at init. */
function collectSpots(){
  walkRoads=[]; comSpots=[]; resSpots=[];
  try{
    if (typeof roadDrawData!=='undefined' && roadDrawData)
      for (var i=0;i<roadDrawData.length;i++){
        var r=roadDrawData[i];
        // no pedestrians spawning on highways (I-20/85/75/285)
        if (r && r.pts && r.pts.length>=2 && r.cat!=='highway') walkRoads.push(r);
      }
  }catch(e){}
  try{
    // OSM types: 0 house, 1 commercial, 2 apartment/large, 3 other
    if (typeof OSM_BUILDINGS!=='undefined' && OSM_BUILDINGS)
      for (var j=0;j<OSM_BUILDINGS.length;j++){
        var b=OSM_BUILDINGS[j];
        if (b && (b[5]===1||b[5]===2)) comSpots.push(b);
      }
  }catch(e){}
  try{
    if (typeof PLACED_HOUSES!=='undefined' && PLACED_HOUSES)
      for (var k=0;k<PLACED_HOUSES.length;k++) resSpots.push(PLACED_HOUSES[k]);
  }catch(e){}
}
/* roadsideSpot() — random point along a random non-highway road, offset
   perpendicular (half-width + 2.5-5.5u, random side) so the spawn is OFF the
   asphalt — pedestrians start on the shoulder/grass, never in traffic. */
function roadsideSpot(){
  var r=walkRoads[(srand()*walkRoads.length)|0];
  var pts=r.pts, si=(srand()*(pts.length-1))|0;
  var a=pts[si], b=pts[si+1], t=srand();
  var x=a[0]+(b[0]-a[0])*t, z=a[1]+(b[1]-a[1])*t;
  var dx=b[0]-a[0], dz=b[1]-a[1], L=Math.hypot(dx,dz)||1;
  var side=srand()<0.5?1:-1, off=r.w/2+2.5+srand()*3;   // off the asphalt
  return [x+(-dz/L)*off*side, z+(dx/L)*off*side];
}
/* nearSpot(list, isOSM) — random point on a ring around a building
   (half the building's footprint + 3-9u out): "near the building" without
   being inside it. isOSM picks the OSM [x,z,w,d,...] layout vs the
   PLACED_HOUSES [x,z,w,d] layout. */
function nearSpot(list, isOSM){
  var s=list[(srand()*list.length)|0];
  var w=isOSM?s[2]:s[2], d=isOSM?s[3]:s[3];
  var ang=srand()*Math.PI*2, dist=Math.max(w,d)/2+3+srand()*6;
  return [s[0]+Math.cos(ang)*dist, s[1]+Math.sin(ang)*dist];
}
/* spawnNPC(id) — creates one NPC data object: up to 12 placement tries
   (55% roadside / 20% commercial / 25% residential, falling back to roadside
   when a pool is empty; [4000,6000] is the last-resort map middle), then
   type by roll (45% man / 40% woman / 15% boy16 — Joshua's age rule: nobody
   under 16, nobody over 65), walk speed by type (boys fastest: 1.6-2.1 u/s),
   0.85 body scale for boys, 3 random body-width variants, and randomized
   skin (brown tones per spec)/shirt/pants. Speeds use srand (stable) at
   spawn; AI uses Math.random per frame. */
function spawnNPC(id){
  var pt=null, tries=0, roll=srand();
  // 55% roadside / 20% commercial / 25% residential (fall back to roadside)
  while (tries<12){
    if (roll<0.55 || (roll<0.75 && !comSpots.length) || (roll>=0.75 && !resSpots.length)){
      if (walkRoads.length) pt=roadsideSpot();
    } else if (roll<0.75){
      pt=nearSpot(comSpots,true);
    } else {
      pt=nearSpot(resSpots,false);
    }
    if (!pt){ pt=[4000,6000]; break; }                 // last-resort map middle
    if (!npcBlocked(pt[0],pt[1])) break;              // good spot
    tries++;
  }
  var tr=srand();
  var type= tr<0.45?0 : (tr<0.85?1:2);                 // 45% men / 40% women / 15% boys
  var n={
    id:id, x:pt[0], z:pt[1], heading:srand()*Math.PI*2,
    state: srand()<0.7?ST_WALK:ST_IDLE,
    stateT: 1+srand()*4, speed: 0, seed: srand(), type: type,
    y:0, phase:srand()*6.28, walkAmt:0, slot:-1,
    lx:pt[0], lz:pt[1], stuckT:0, fails:0, _pick:false,
    scl:  type===2?0.85:1.0,                          // 16yo boys: 0.85 scale
    wid:  type===2?0.9:[0.9,1.0,1.18][(srand()*3)|0],  // 3 body-type widths
    skin: SKINS[(srand()*SKINS.length)|0],
    shirt:SHIRTS[(srand()*SHIRTS.length)|0],
    pants:PANTS[(srand()*PANTS.length)|0]
  };
  n.speed = type===0 ? 1.3+srand()*0.4 : type===1 ? 1.2+srand()*0.4 : 1.6+srand()*0.5;
  try{ n.y=(typeof clampVehY==='function')?clampVehY(n.x,n.z,heightAt(n.x,n.z)):heightAt(n.x,n.z); }catch(e){ n.y=0; }
  n.lx=n.x; n.lz=n.z;
  return n;
}

/* ---------------- free-think AI ----------------
   No waypoints, no pathfinding. WALK a heading for a few seconds, IDLE and
   look around, TURN to a new heading. Sample ahead; if blocked, TURN.
   PERF trick: the lookahead probe and stuck check are staggered per NPC
   ((npcTick+n.id)%18 and %60) so only ~1/18th of the population probes per
   frame — 1000 NPCs × probes every frame would be too slow on the TCL. */
/* aiNPC(n, dt) — one AI tick:
     WALK: advance along heading; every ~0.3s probe 3.2u ahead and TURN if
       blocked; every ~1s check displacement (moved <0.6u while walking =
       stuck): after 5s file a glitch and TURN; unexpected deep water also
       files a glitch. Timer end → 35% IDLE, else TURN.
     IDLE: gentle sinusoidal heading wander (look around), no position drift.
     TURN: pick a random new heading, probe it; walk it if clear, else retry —
       after 10 failed turns file a glitch and walk anyway (the stuck
       detector watches; better to keep moving than spin forever). */
/* setState(n, st, t) — sets the NPC's AI state and its countdown timer. */
function setState(n, st, t){ n.state=st; n.stateT=t; }
function aiNPC(n, dt){
  n.stateT-=dt;
  if (n.state===ST_WALK){
    var step=n.speed*dt;
    n.x+=Math.sin(n.heading)*step;
    n.z+=Math.cos(n.heading)*step;
    // staggered lookahead probe (~every 0.3s per NPC at 60fps)
    if ( ((npcTick+n.id)%18)===0 ){
      var px=n.x+Math.sin(n.heading)*3.2, pz=n.z+Math.cos(n.heading)*3.2;
      if (npcBlocked(px,pz)){ n.fails++; setState(n,ST_TURN,0); }
    }
    // staggered stuck check (~every 1s): moved <0.6u while walking = stuck
    if ( ((npcTick+n.id)%60)===0 ){
      var dx=n.x-n.lx, dz=n.z-n.lz;
      if (dx*dx+dz*dz < 0.36){ n.stuckT++; } else { n.stuckT=0; }
      n.lx=n.x; n.lz=n.z;
      if (n.stuckT>=5){
        npcGlitch(n,'stuck on geometry for >5s','WALK','heading somewhere');
        n.stuckT=0; n.fails=0; setState(n,ST_TURN,0);
      }
      // deep water should never happen (probes avoid it) — report if it does
      try{
        if (typeof waterDepthAt==='function' && waterDepthAt(n.x,n.z)>1.2){
          npcGlitch(n,'entered deep water unexpectedly','WALK','heading somewhere');
          setState(n,ST_TURN,0);
        }
      }catch(e){}
    }
    if (n.stateT<=0){
      if (Math.random()<0.35) setState(n,ST_IDLE,1+Math.random()*2);  // pause, look around
      else setState(n,ST_TURN,0);
    }
  }
  else if (n.state===ST_IDLE){
    // "look around": gentle sinusoidal heading wander, no drift
    n.heading+=Math.sin(npcTick*0.05+n.seed*6.283)*0.4*dt;
    if (n.stateT<=0) setState(n,ST_TURN,0);
  }
  else { // ST_TURN: pick a heading, verify it, walk it — or try another
    n.heading+=(Math.random()*2-1)*2.4;
    var tx=n.x+Math.sin(n.heading)*3.2, tz=n.z+Math.cos(n.heading)*3.2;
    if (!npcBlocked(tx,tz)){
      n.fails=0; setState(n,ST_WALK,2.5+Math.random()*3.5);
    } else {
      n.fails++;
      if (n.fails>10){
        npcGlitch(n,'blocked repeatedly ('+n.fails+' failed turns)','TURN',
                  'trying to find a walkable heading');
        n.fails=0; setState(n,ST_WALK,2);   // walk anyway; stuck-detector watches
      }
    }
  }
}

/* ---------------- streaming: bodies only near the camera ---------------- */
/* assignSlot(s,n) — binds NPC n to render slot s and bakes its per-instance
   colors: skin on head+arms (short-sleeve look), shirt on torso, pants on
   legs. Slot count is set to the visible count each frame; unassigned slots
   are never drawn. */
function assignSlot(s,n){
  n.slot=s; slots[s]=n;
  _col.set(n.skin);
  _mesh.head.setColorAt(s,_col); _mesh.armL.setColorAt(s,_col); _mesh.armR.setColorAt(s,_col);
  _col.set(n.shirt); _mesh.torso.setColorAt(s,_col);
  _col.set(n.pants); _mesh.legL.setColorAt(s,_col); _mesh.legR.setColorAt(s,_col);
  var mk=[_mesh.torso,_mesh.head,_mesh.armL,_mesh.armR,_mesh.legL,_mesh.legR];
  for (var i=0;i<mk.length;i++) if (mk[i].instanceColor) mk[i].instanceColor.needsUpdate=true;
}
/* refreshSlots(px,pz) — reassigns the 40 render slots every 0.5s: releases
   NPCs beyond HIDE_R (200u — hysteresis so bodies don't pop at the
   VISIBLE_R 150u boundary), then fills freed slots with the nearest
   unslotted NPCs inside VISIBLE_R. No allocation: a _pick flag on each NPC
   prevents double-picking within one pass, and _free is a reused scratch
   array. Note: the fill scan is O(slots × npcs) — acceptable at 0.5s
   cadence, would not be per frame. */
function refreshSlots(px,pz){
  var VR2=VISIBLE_R*VISIBLE_R, HR2=HIDE_R*HIDE_R, i, s, n;
  _free.length=0;
  for (s=0;s<MAX_VISIBLE;s++){
    n=slots[s];
    if (n){
      var dx=n.x-px, dz=n.z-pz;
      if (dx*dx+dz*dz>HR2){ n.slot=-1; slots[s]=null; _free.push(s); }
    } else _free.push(s);
  }
  // fill freed slots with the nearest unslotted NPCs (no allocation: flag scan)
  for (var f=0;f<_free.length;f++){
    var best=null, bestD=VR2;
    for (i=0;i<npcs.length;i++){
      n=npcs[i];
      if (n.slot>=0||n._pick) continue;
      var ex=n.x-px, ez=n.z-pz, d2=ex*ex+ez*ez;
      if (d2<bestD){ bestD=d2; best=n; }
    }
    if (!best) break;
    best._pick=true; assignSlot(_free[f],best);
  }
  for (i=0;i<npcs.length;i++) npcs[i]._pick=false;
}

/* ---------------- rendering: 6 InstancedMeshes, ~6-10 boxes per NPC ----------------
   One unit box per part, scaled by matrix. Per-instance colors: skin on head
   + arms (short-sleeve look), shirt on torso, pants on legs. Boys render at
   0.85 scale; 3 width variants via wid. */
/* partMat(...) — composes one body-part's matrix from 7 premultiplied
   matrices: world translate → yaw → body scale → part offset → limb swing
   (rotation X) → pivot drop → part size. All scratch matrices are allocated
   once at init (never in the hot loop); _out is returned. */
function partMat(wx,wy,wz,yaw,scl, px,py,pz, swing,drop, sx,sy,sz){
  _m1.makeTranslation(wx,wy,wz);
  _m2.makeRotationY(yaw);
  _m3.makeScale(scl,scl,scl);
  _m4.makeTranslation(px,py,pz);
  _m5.makeRotationX(swing);
  _m6.makeTranslation(0,drop,0);
  _m7.makeScale(sx,sy,sz);
  return _out.copy(_m1).multiply(_m2).multiply(_m3)
              .multiply(_m4).multiply(_m5).multiply(_m6).multiply(_m7);
}
/* renderNPCs(dt,px,pz) — writes body-part matrices for every slotted NPC.
   walkAmt eases toward 1 (walking) / 0 (idle) so limbs don't snap; the walk
   phase advances at 3.2+speed*2.6 rad/s; legs swing opposed (sw / -sw),
   arms counter-swing (asw / -asw); distant NPCs get a static pose
   (ANIM_R=80u LOD — animation only near the camera). A non-finite terrain
   height is reported as a "fell through world" glitch and clamped to the
   last good height. */
function renderNPCs(dt,px,pz){
  var s, n, vis=0, AR2=ANIM_R*ANIM_R;
  for (s=0;s<MAX_VISIBLE;s++){
    n=slots[s]; if(!n) continue;
    vis++;
    var dx=n.x-px, dz=n.z-pz, near=(dx*dx+dz*dz)<AR2;
    var y; try{ y=heightAt(n.x,n.z); }catch(e){ y=NaN; }
    if (!isFinite(y)){
      npcGlitch(n,'fell through world','WALK','standing on terrain');
      y=isFinite(n.y)?n.y:0;
    }
    if (typeof clampVehY==='function') y=clampVehY(n.x,n.z,y);  // v1.12: ground clamp — no sky-floaters
    n.y=y;
    var target=(n.state===ST_WALK)?1:0;
    n.walkAmt+=(target-n.walkAmt)*Math.min(1,6*dt);
    if (near && n.walkAmt>0.02) n.phase+=dt*(3.2+n.speed*2.6)*n.walkAmt;
    var sw=Math.sin(n.phase)*0.55*n.walkAmt;       // legs oppose...
    var asw=Math.sin(n.phase)*0.45*n.walkAmt;      // ...arms counter-swing
    if (!near){ sw=0; asw=0; }                    // distant: static pose
    var scl=n.scl, yaw=n.heading, wid=n.wid;
    _mesh.torso.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, 0,1.075,0, 0,0, 0.42*wid,0.55,0.26*wid));
    _mesh.head.setMatrixAt (s, partMat(n.x,y,n.z,yaw,scl, 0,1.49,0,  0,0, 0.24,0.28,0.24));
    _mesh.armL.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, -0.265*wid,1.28,0, -asw,-0.29, 0.11,0.58,0.11));
    _mesh.armR.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl,  0.265*wid,1.28,0,  asw,-0.29, 0.11,0.58,0.11));
    _mesh.legL.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, -0.115*wid,0.80,0,  sw,-0.33, 0.15,0.66,0.15));
    _mesh.legR.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl,  0.115*wid,0.80,0, -sw,-0.33, 0.15,0.66,0.15));
  }
  visCount=vis;
  var mk=[_mesh.torso,_mesh.head,_mesh.armL,_mesh.armR,_mesh.legL,_mesh.legR];
  for (var i=0;i<mk.length;i++){ mk[i].count=vis; mk[i].instanceMatrix.needsUpdate=true; }
}

/* publishReport() — pushes the NPC status to the Report panel every 5s:
   population, visible count, and the live glitch log (Joshua's NPC QA
   dispatch calls). Guarded — safe when Report isn't loaded. */
function publishReport(){
  try{
    if (typeof Report!=='undefined' && Report.setSys){
      Report.setSys('npc',{
        count:npcs.length, visible:visCount, maxVisible:MAX_VISIBLE,
        glitchReports:glitchLog.slice(), glitchTotal:glitchTotal,
        note:'free-think pedestrians (WALK/IDLE/TURN, no waypoints); bodies stream in under 150u'
      });
    }
  }catch(e){}
}

/* ---------------- init ---------------- */
/* initNPCs() — allocates scratch matrices, builds the border, fills spawn
   pools, creates all 1000 NPCs, the 40 render slots, and the 6
   InstancedMeshes (one per body part, unit-box geometry scaled per part).
   Meshes are frustumCulled=false (positions update every frame; culling the
   batch would hide everyone) with cast/receive shadows off for perf. */
function initNPCs(){
  _m1=new THREE.Matrix4(); _m2=new THREE.Matrix4(); _m3=new THREE.Matrix4();
  _m4=new THREE.Matrix4(); _m5=new THREE.Matrix4(); _m6=new THREE.Matrix4();
  _m7=new THREE.Matrix4(); _out=new THREE.Matrix4();
  _col=new THREE.Color();
  buildBorder();
  collectSpots();
  for (var i=0;i<NPC_COUNT;i++) npcs.push(spawnNPC(i));
  for (var s=0;s<MAX_VISIBLE;s++) slots.push(null);
  var unitBox=new THREE.BoxGeometry(1,1,1);
  function im(){
    var m=new THREE.InstancedMesh(unitBox,
      new THREE.MeshLambertMaterial({color:0xffffff}), MAX_VISIBLE);
    m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
    m.frustumCulled=false;      // positions update every frame; never cull the batch
    m.castShadow=false; m.receiveShadow=false;
    m.count=0; scene.add(m); return m;
  }
  _mesh={ torso:im(), head:im(), armL:im(), armR:im(), legL:im(), legR:im() };
  npcReady=true;
  publishReport();
}

/* tryInit() — waits for the main script's world (THREE, scene,
   roadDrawData) to exist, then inits once. ~20s grace (40 × 500ms); after
   that the NPC system stays off and the game is unaffected. */
var initTries=0;
function tryInit(){
  try{
    if (typeof THREE==='undefined' || typeof scene==='undefined' ||
        typeof roadDrawData==='undefined' || !roadDrawData || !roadDrawData.length){
      if (++initTries<40) setTimeout(tryInit,500);   // ~20s grace
      return;
    }
    initNPCs();
  }catch(e){ /* NPC system stays off; game unaffected */ }
}

/* ---------------- main-loop entry ---------------- */
/* updateNPCs(dt, playerPos) — frame tick (wired by the build agent into
   animate()): AI for all 1000 NPCs always runs (data-only), slots refresh
   every 0.5s, bodies render, Report publishes every 5s. When the player is
   driving, the streaming center follows the CAR, not the player on foot.
   dt clamped to 50ms. Never throws. */
function updateNPCs(dt, playerPos){
  if (!npcReady) return;
  try{
    dt=Math.min(0.05, dt||0.016);
    npcTick++;
    var px, pz;
    if (playerPos && isFinite(playerPos.x)){ px=playerPos.x; pz=playerPos.z; }
    else if (typeof player!=='undefined' && player){ px=player.x; pz=player.z; }
    else return;
    try{ if (typeof car!=='undefined' && car && car.driving){ px=car.x; pz=car.z; } }catch(e){}
    var i;
    for (i=0;i<npcs.length;i++) aiNPC(npcs[i],dt);   // data-only, always runs
    streamT-=dt;
    if (streamT<=0){ streamT=0.5; refreshSlots(px,pz); }
    renderNPCs(dt,px,pz);
    repT-=dt;
    if (repT<=0){ repT=5; publishReport(); }
  }catch(e){}
}
window.updateNPCs=updateNPCs;
/* debug handle for the inspector rig: window.NPC_DEBUG.npcs / .glitches */
window.NPC_DEBUG={ get npcs(){return npcs;}, get glitches(){return glitchLog;} };

tryInit();
})();
