/* ============================================================================
   FILE: npc_system.js — "Surviving Adamsville" pedestrian system (~1,000 NPCs)
   ----------------------------------------------------------------------------
   PURPOSE: Free-thinking pedestrian population streaming around the player.
   KEY SYSTEMS:
     - Population: NPC_COUNT=1000 plain data objects (positions only) — no
       geometry unless near the player. Placement is DETERMINISTIC (seeded
       mulberry32, seed 19951013): stable spawns across loads. AI uses
       Math.random (non-deterministic behavior).
     - Free-think AI: no waypoints, no pathfinding — WALK a heading for a few
       seconds, IDLE (look around), TURN to a new heading; a 3.2u lookahead
       probe turns the NPC away from blockages. Simple sim, Joshua's rule.
     - Streaming renderer: only MAX_VISIBLE=40 bodies within 150u of the
       camera get instanced bodies (hysteresis: released beyond 200u), 6
       InstancedMeshes (torso/head/2 arms/2 legs), per-instance colors
       (skin head+arms = short-sleeve look, shirt torso, pants legs).
       Limb animation only within 80u (LOD); distant bodies are static.
       TCL T513V (Joshua's phone) budget drove these caps.
     - Border containment: BORDER convex quad → inward half-planes, 10u inner
       margin; NPCs turn around at the world edge instead of walking out.
     - NPC QA testers: every NPC files "glitch dispatch calls" into the
       Report when stuck >5s, blocked >10 failed turns, or in deep water —
       Joshua's live audit of broken geometry.
   JOSHUA SPECS ENCODED:
     - NPC population ~1,000: adult men (~45%), adult women (~40%), and a
       smaller number of 16-year-old boys (~15%). NOBODY under 16, NOBODY
       over 65 — hard rule, encoded in TYPE_NAMES and the age-16 boy model
       (0.85 scale). No children, no elderly.
     - Pedestrians never spawn on highways (I-20/85/75/285).
     - Spawn mix: 55% roadside (off the asphalt: half-width + 2.5-5.5u),
       20% commercial, 25% residential.
     - LIFE SIM (queued, not yet in this file): each NPC can have a home
       residence, a car, and a workplace — unassigned shows "unspecified";
       Joshua assigns homes from a dropdown of houses/apartments. Building
       entry is fade/morph-through-the-door (no door animation) — NPC
       disappears inside a while, reappears when leaving.
   ============================================================================ */
/* ============================================================================
   NPC PEDESTRIAN SYSTEM — "Surviving Adamsville" v1.20
   v1.20 SOLID WORLD (Joshua 2026-10-09): NPCs cannot walk through trees,
   buildings, vehicles, or each other. npcColGrid (cell 20u) covers all
   static colliders[] (tree trunks r=0.8, sign posts, light poles); per-frame
   npcHash (cell 4u, persistent arrays) drives NPC-NPC separation; vehicle
   blockers (van, MARTA buses, traffic cars, semis, school buses) refresh
   4x/sec. Boarding/transit NPCs are exempt from vehicle blocking so they
   can REACH their bus/train.
   ----------------------------------------------------------------------------
   v1.21 PLAYER-SOLID (Joshua's bug report 2026-10-09 ~11pm: an NPC "walked
   right through me"). Collision was one-way: the player was blocked by NPC
   bodies, but NPC movement never treated the player as an obstacle. Now the
   on-foot player is solid to NPCs — npcBlocked() refuses steps into the
   player's body space (NPC_PLAYER_R=1.1u) and separateFromPlayer() pushes
   NPCs out after every move. TALK is preserved (1.1u << TALK_R 4.5u).
   The player only counts when on foot (not driving/inside/on transit);
   when driving, the car is already a vehicle blocker.
   ----------------------------------------------------------------------------
   v1.9
   ~1,000 free-think pedestrians. Each NPC is DATA ONLY when distant
   (no geometry, no Three.js objects). Bodies stream in as instanced boxes
   only near the camera. Every NPC is also a QA tester: when one hits a
   problem it files a glitch dispatch call into the Report.

   ---- INTEGRATION (build agent: 2 steps, do NOT edit this file) ----
   1. In index.html, AFTER the main inline <script>...</script> block
      (right before </body>), add:
          <script src="npc_system.js"></script>
      (Must load after the main script: it needs roadDrawData, PLACED_HOUSES,
      bldgGrid, BORDER, heightAt(), onRoad(), inWater(), waterDepthAt(),
      Report, THREE and scene to exist.)
   2. In animate(), after updateCamera(dt); add:
          try{ updateNPCs(dt, player.mesh.position); }catch(e){}

   Reads (all optional/guarded — the system degrades gracefully if one is
   missing): player, car, roadDrawData, PLACED_HOUSES, OSM_BUILDINGS,
   bldgGrid, BORDER, heightAt, onRoad, inWater, waterDepthAt, Report.
   Writes: 6 InstancedMeshes added to scene; window.updateNPCs;
   Report.setSys('npc', ...) every 5s.
   ============================================================================ */
(function npcPedestrians(){
'use strict';

/* ---------------- config ---------------- */
var NPC_COUNT   = 1000;   // Joshua's spec: ~1,000 pedestrians
var MAX_VISIBLE = 40;     // hard cap on instanced bodies (TCL T513V budget)
var VISIBLE_R   = 150;    // stream a body in within this distance (u)
var HIDE_R      = 200;    // release the body beyond this distance (hysteresis)
var ANIM_R      = 80;     // limb animation only inside this range (LOD)
var ST_WALK = 0, ST_IDLE = 1, ST_TURN = 2;
var STATE_NAMES = ['WALK','IDLE','TURN'];
var TYPE_NAMES  = ['man','woman','boy16'];   // nobody under 16, nobody over 65
/* v1.17 transit commuters (Joshua's citizen rule 2026-10-09): if a citizen
   is catching a bus they MUST stand at a bus stop; train riders wait on the
   station platform. ~22% of NPCs are bus commuters, ~6% train commuters. */
var TR_BUS_R=0.22, TR_TRAIN_R=0.06;   // commuter mix at spawn
var TR_WAIT_T=300;                    // give up waiting after 5 min
var TR_GOTO_T=150;                    // give up walking to a stop after 2.5 min
var TR_BOARD_T=10;                    // give up reaching the vehicle after 10s
var TR_ARRIVE_R=4;                     // arrival radius at a stop/station (u)

/* 1995-Atlanta palettes. Skin: range of brown tones (per spec). */
var SKINS  = [0x4a2f1c,0x5a3a24,0x6b4429,0x7d5230,0x8a5f36,0x93683c,0xa07a48];
var SHIRTS = [0xc23b2e,0x2e5fa3,0x2e8b57,0xe0e0e0,0xe8b923,0x1f8a8a,0xd96c2c,
              0x7b4fa3,0x555c66,0x222226,0xb03060,0x3a7d44,0xc7c7c7,0x8a2be2];
var PANTS  = [0x2e4a6b,0x1f2a3a,0x141414,0x9a8a6a,0x5a4632,0x666c75,0x3b3f4a];

/* ---------------- state ---------------- */
var npcs=[];            // the population: plain data objects, nothing else
var slots=[];           // MAX_VISIBLE entries: npc ref or null
var glitchLog=[];       // newest 50 dispatch calls
var glitchTotal=0;
var npcReady=false, npcTick=0, visCount=0;
var streamT=0, repT=0;

/* scratch / temps — allocated once, never in the hot loop */
var _m1=null,_m2=null,_m3=null,_m4=null,_m5=null,_m6=null,_m7=null,_out=null;
var _col=null, _free=[], _mesh=null;   // _mesh: {torso,head,armL,armR,legL,legR}
var walkRoads=[], comSpots=[], resSpots=[];
var borderOK=null;      // null = no constraint; else {px,py...} half-planes

/* Deterministic RNG for PLACEMENT ONLY (stable spawns). AI uses Math.random. */
function mulberry32(a){
  return function(){
    a|=0; a=a+0x6D2B79F5|0;
    var t=Math.imul(a^a>>>15,1|a);
    t=t+Math.imul(t^t>>>7,61|t)^t;
    return ((t^t>>>14)>>>0)/4294967296;
  };
}
var srand=mulberry32(19951013);

/* ---------------- border containment ----------------
   BORDER is a convex quad [{x,z}x4]. Precompute inward half-planes so NPCs
   TURN around instead of wandering out of the world. 10u inner margin. */
/* buildBorder() — precomputes the BORDER polygon's inward-facing half-planes
   (one per edge) so insideBorder() can cheaply test containment. BORDER is a
   convex quad; edge direction follows the polygon's winding (s=+1/-1). */
function buildBorder(){
  try{
    if (typeof BORDER==='undefined'||!BORDER||BORDER.length<3){ borderOK=null; return; }
    var n=BORDER.length, i, area=0;
    for (i=0;i<n;i++){ var a=BORDER[i], b=BORDER[(i+1)%n]; area+=a.x*b.z-b.x*a.z; }
    var s=area>0?1:-1, E=[];
    for (i=0;i<n;i++){
      var p=BORDER[i], q=BORDER[(i+1)%n];
      var ex=q.x-p.x, ez=q.z-p.z, L=Math.hypot(ex,ez)||1;
      E.push({px:p.x,pz:p.z,ex:ex/L,ez:ez/L,s:s});
    }
    borderOK=E;
  }catch(e){ borderOK=null; }
}
/* insideBorder(x,z) — true when (x,z) is at least 10u inside every border
   edge. The 10u margin keeps NPCs off the world wall. Returns true when no
   border constraint exists. */
function insideBorder(x,z){
  if (!borderOK) return true;
  for (var i=0;i<borderOK.length;i++){
    var e=borderOK[i];
    var cr=e.ex*(z-e.pz)-e.ez*(x-e.px);   // cross(edge, point-p)
    if (e.s*cr < 10) return false;        // 10u margin inside the wall
  }
  return true;
}

/* ---------------- blockage probe ----------------
   Cheap "can I step here?" test: water, road corridor, OSM building
   colliders (spatial grid, cell 40u — same grid the game uses), ranch
   houses (PLACED_HOUSES is small, direct loop), static world colliders
   (trees/signs/poles via npcColGrid, cell 20u), and vehicles (van, MARTA
   buses, traffic cars, semis, school buses — refreshed 4x/sec).
   v1.20 SOLID WORLD (Joshua 2026-10-09): NPCs cannot walk through trees,
   buildings, vehicles, or each other. The old "trees intentionally ignored"
   rule is GONE — a trunk is solid. */
/* npcColGrid — v1.20 spatial hash (cell 20u) over the world's static
   colliders[] (trees r=0.8, sign posts r=0.4, light poles, small structures).
   Built once at init; NPCs are blocked by every solid object, not just
   buildings. Huge area colliders (r>20, POI zones) are skipped — NPC spawn
   logic already avoids those districts, and including them would wall off
   whole neighborhoods. */
var npcColGrid=null;
var NPC_COL_CELL=20;
function buildNpcColGrid(){
  npcColGrid={};
  try{
    if (typeof colliders==='undefined' || !colliders) return;
    for (var i=0;i<colliders.length;i++){
      var c=colliders[i];
      if (!c || c.r>20) continue;   // skip POI-scale area colliders
      var k=Math.floor(c.x/NPC_COL_CELL)+','+Math.floor(c.z/NPC_COL_CELL);
      (npcColGrid[k]=npcColGrid[k]||[]).push(c);
    }
  }catch(e){}
}
/* npcHitsStatic(x,z) — v1.20: true if (x,z) is inside any static world
   collider (tree trunk, sign post, light pole, small structure). NPC body
   radius ~0.5u is added to the collider radius. */
function npcHitsStatic(x,z){
  if (!npcColGrid) return false;
  try{
    var cx=Math.floor(x/NPC_COL_CELL), cz=Math.floor(z/NPC_COL_CELL);
    for (var gx=cx-1;gx<=cx+1;gx++) for (var gz=cz-1;gz<=cz+1;gz++){
      var cell=npcColGrid[gx+','+gz]; if(!cell) continue;
      for (var i=0;i<cell.length;i++){
        var c=cell[i], dx=x-c.x, dz=z-c.z, rr=c.r+0.5;
        if (dx*dx+dz*dz < rr*rr) return true;
      }
    }
  }catch(e){}
  return false;
}
/* npcVehicleBlocked(x,z,n) — v1.20: true if (x,z) is inside a vehicle.
   Checks the player's van (when parked/slow), MARTA buses, AI traffic cars,
   semis, and school buses. NPCs already avoid road corridors via onRoad(),
   so this catches parked vehicles, dwelling buses at stops (commuters walk
   TO stops — they must not walk THROUGH the bus), and the van on grass.
   EXEMPTION: an NPC actively boarding (n.boarding) or walking to transit
   (n.goto) skips this check — it needs to REACH the vehicle, and the
   boarding logic handles the final approach. */
var _vehList=[], _vehListT=0;
function refreshVehList(nowMs){
  if (nowMs-_vehListT < 250) return;   // refresh at most 4x/sec
  _vehListT=nowMs; _vehList.length=0;
  try{
    // player van — solid when parked or crawling (fast van is on roads,
    // which NPCs already avoid via onRoad)
    if (typeof car!=='undefined' && car && (!car.driving || (car.speed||0)<5))
      _vehList.push({x:car.x, z:car.z, r:2.6});
  }catch(e){}
  try{
    var MB=window.MARTA_BUS;
    if (MB && MB.buses) for (var i=0;i<MB.buses.length;i++){
      var b=MB.buses[i]; if(b) _vehList.push({x:b.x, z:b.z, r:3.2});
    }
  }catch(e){}
  try{
    var TRF=window.TRAFFIC;
    if (TRF && TRF.cars) for (var j=0;j<TRF.cars.length;j++){
      var tc=TRF.cars[j]; if(tc) _vehList.push({x:tc.x, z:tc.z, r:2.2});
    }
  }catch(e){}
  try{
    var SE=window.SEMIS;
    if (SE && SE.semis) for (var k=0;k<SE.semis.length;k++){
      var s=SE.semis[k]; if(s) _vehList.push({x:s.x, z:s.z, r:4.2});
    }
  }catch(e){}
  try{
    var SBA=window.__sbActive;   // school buses with sign out (dwell)
    if (SBA) for (var m=0;m<SBA.length;m++){
      var sb=SBA[m]; if(sb) _vehList.push({x:sb.x, z:sb.z, r:3.2});
    }
  }catch(e){}
}
/* ---------------- NPC-NPC collision (v1.20) ----------------
   JOSHUA'S RULE (2026-10-09): NPCs cannot walk through each other.
   Per-frame spatial hash (cell 4u) over all 1,000 NPC positions; after an
   NPC moves, separateNPC() pushes it out of any neighbor's body space.
   The hash uses PERSISTENT cell arrays (cleared, never reallocated) so the
   per-frame rebuild creates zero garbage — TCL-safe. Separation is soft:
   each NPC moves only itself, so pairs resolve symmetrically over frames
   without oscillation. NPC body radius ~0.5u -> 1.0u min separation. */
var npcHash={};
var NPC_HASH_CELL=4;
function rebuildNpcHash(){
  for (var k in npcHash){ npcHash[k].length=0; }  // clear, keep arrays
  for (var i=0;i<npcs.length;i++){
    var n=npcs[i];
    var key=Math.floor(n.x/NPC_HASH_CELL)+','+Math.floor(n.z/NPC_HASH_CELL);
    var arr=npcHash[key];
    if (!arr){ arr=npcHash[key]=[]; }
    arr.push(n);
  }
}
/* separateNPC(n) — push n out of overlapping NPC body space. Called after
   every NPC position change (WALK step, goto step, boarding step, settle).
   Only moves n itself — the neighbor resolves itself on its own tick. */
function separateNPC(n){
  try{
    var cx=Math.floor(n.x/NPC_HASH_CELL), cz=Math.floor(n.z/NPC_HASH_CELL);
    for (var gx=cx-1;gx<=cx+1;gx++) for (var gz=cz-1;gz<=cz+1;gz++){
      var cell=npcHash[gx+','+gz]; if(!cell) continue;
      for (var i=0;i<cell.length;i++){
        var o=cell[i];
        if (o===n) continue;
        var dx=n.x-o.x, dz=n.z-o.z, d2=dx*dx+dz*dz;
        if (d2 < 1.0 && d2 > 0.0001){
          var d=Math.sqrt(d2), push=(1.0-d)/d*0.5;
          n.x+=dx*push; n.z+=dz*push;
        }
      }
    }
  }catch(e){}
}
/* npcNearOther(x,z,r) — v1.20: true if another NPC is within r of (x,z).
   Used by the lookahead probe so NPCs TURN away from crowds instead of
   walking into them. */
function npcNearOther(x,z,r){
  try{
    var cx=Math.floor(x/NPC_HASH_CELL), cz=Math.floor(z/NPC_HASH_CELL);
    var r2=r*r;
    for (var gx=cx-1;gx<=cx+1;gx++) for (var gz=cz-1;gz<=cz+1;gz++){
      var cell=npcHash[gx+','+gz]; if(!cell) continue;
      for (var i=0;i<cell.length;i++){
        var o=cell[i], dx=x-o.x, dz=z-o.z;
        if (dx*dx+dz*dz < r2) return true;
      }
    }
  }catch(e){}
  return false;
}
/* ---------------- player collision (v1.21) ----------------
   JOSHUA'S BUG REPORT (2026-10-09 ~11pm): an NPC "walked right through
   me". Player->NPC collision already existed (the player is blocked by
   NPC bodies), but NPC movement never treated the player as an obstacle —
   every path (WALK step, goto sidestep, boarding step, settle, spawn
   placement) went through npcBlocked(), which knew nothing about the
   player. Now it does:
     - npcHitsPlayer(x,z): true when the on-foot player is within
       NPC_PLAYER_R of (x,z). Wired into npcBlocked() so the lookahead
       probe TURNs away and steps refuse — the same gate walls, trees,
       and vehicles use.
     - separateFromPlayer(n): soft push-out after every move (mirrors
       separateNPC), so an NPC can never end a frame overlapping the
       player even if a probe missed.
   TALK is preserved: NPC_PLAYER_R (1.1u) sits far inside TALK_R (4.5u),
   so NPCs stop at a respectful distance but stay talkable. The player
   only counts when on foot (npcTalkEligible: not driving, not inside, not
   on transit) — when driving, the car itself is already a vehicle blocker
   via npcHitsVehicle. The per-frame cache (_ppx/_ppz/_ppOnFoot) is written
   once in updateNPCs so the hot probe path stays two subtractions plus a
   compare — TCL-safe. */
var NPC_PLAYER_R=1.1;   // player body ~0.5u + NPC body ~0.5u + margin
var _ppx=0, _ppz=0, _ppOnFoot=false;   // per-frame player cache (see updateNPCs)
/* cachePlayerPos() — snapshot the on-foot player once per frame. Called
   from updateNPCs before any NPC ticks run. A missing player reads as
   "not on foot" so NPCs never freeze for a phantom. */
function cachePlayerPos(){
  _ppOnFoot=false;
  try{
    if (typeof player!=='undefined' && player && isFinite(player.x) && isFinite(player.z)){
      _ppx=player.x; _ppz=player.z;
      _ppOnFoot=npcTalkEligible();
    }
  }catch(e){}
}
/* npcHitsPlayer(x,z) — true if the on-foot player is within NPC_PLAYER_R
   of (x,z). Reads the per-frame cache; never throws. */
function npcHitsPlayer(x,z){
  if (!_ppOnFoot) return false;
  try{
    var dx=x-_ppx, dz=z-_ppz, rr=NPC_PLAYER_R;
    return (dx*dx+dz*dz) < rr*rr;
  }catch(e){ return false; }
}
/* separateFromPlayer(n) — push n out of the player's body space after a
   move. Mirrors separateNPC: moves only the NPC, never the player, so
   crowded pairs resolve without oscillation. */
function separateFromPlayer(n){
  if (!_ppOnFoot) return;
  try{
    var dx=n.x-_ppx, dz=n.z-_ppz, d2=dx*dx+dz*dz, rr=NPC_PLAYER_R;
    if (d2 < rr*rr && d2 > 0.0001){
      var d=Math.sqrt(d2), push=(rr-d)/d;
      n.x+=dx*push; n.z+=dz*push;
    }
  }catch(e){}
}
function npcHitsVehicle(x,z,n){  // boarding / walking-to-transit NPCs must REACH their vehicle
  if (n && (n.boarding || n.goto)) return false;
  try{ refreshVehList(Date.now()); }catch(e){}
  for (var i=0;i<_vehList.length;i++){
    var v=_vehList[i], dx=x-v.x, dz=z-v.z, rr=v.r+0.5;
    if (dx*dx+dz*dz < rr*rr) return true;
  }
  return false;
}
/* npcBlocked(x,z,n) — cheap "can I step here?" probe. Returns true for water,
   road corridors, border edges, OSM building colliders (40u spatial grid —
   the same grid the game uses), ranch houses (small list, direct loop),
   static world colliders (trees/signs/poles — v1.20 npcColGrid), and
   vehicles (v1.20). n is the NPC asking (optional) — used for the
   boarding/transit vehicle exemption. All wrapped — a missing world feature
   degrades to "not blocked". */
function npcBlocked(x,z,n){
  try{
    if (typeof inWater==='function' && inWater(x,z)) return true;
    if (typeof onRoad==='function' && onRoad(x,z)) return true;
    if (!insideBorder(x,z)) return true;
    if (typeof bldgGrid!=='undefined' && bldgGrid){
      var cx=Math.floor(x/40), cz=Math.floor(z/40);
      for (var gx=cx-1;gx<=cx+1;gx++) for (var gz=cz-1;gz<=cz+1;gz++){
        var cell=bldgGrid[gx+','+gz]; if(!cell) continue;
        for (var i=0;i<cell.length;i++){
          var c=cell[i], dx=x-c.x, dz=z-c.z, rr=c.r+0.7;
          if (dx*dx+dz*dz < rr*rr) return true;
        }
      }
    }
    if (typeof PLACED_HOUSES!=='undefined' && PLACED_HOUSES){
      for (var j=0;j<PLACED_HOUSES.length;j++){
        var h=PLACED_HOUSES[j];
        var hx=x-h[0], hz=z-h[1], hr=Math.max(h[2],h[3])/2+1.7;
        if (hx*hx+hz*hz < hr*hr) return true;
      }
    }
    if (npcHitsStatic(x,z)) return true;      // v1.20: trees/signs/poles
    if (npcHitsVehicle(x,z,n)) return true;   // v1.20: vehicles
    if (npcHitsHeroHouse(x,z)) return true;   // v3.1: 535 Dollar Mill Rd
    if (npcHitsPlayer(x,z)) return true;      // v1.21: the player is solid to NPCs (Joshua 2026-10-09 bug: NPC walked through him)
  }catch(e){}
  return false;
}
/* npcHitsHeroHouse(x,z) — v3.1 (2026-10-09 inspection): the hero house at 535
   Dollar Mill Rd is not in PLACED_HOUSES and its wall segments are never
   consulted by NPC logic — NPCs could walk through the walls. NPCs never
   enter the hero house (the player uses the action button), so the full
   footprint counts as solid, including the door gaps. Reads the live
   window.heroHouse / window.HOUSE_535 constants; degrades to false if the
   house isn't built yet. */
function npcHitsHeroHouse(x,z){
  try{
    var hh=window.heroHouse, H=window.HOUSE_535;
    if (!hh || hh.cx===undefined || !H) return false;
    var m=0.9; // wall thickness + NPC body radius
    var hw=H.W/2+m, hd=H.D/2+m;
    if (x>hh.cx-hw && x<hh.cx+hw && z>hh.cz-hd && z<hh.cz+hd) return true;
    // entry-stair strip (south): the treads are solid underfoot for the
    // player via heroPorchY, but NPCs have no stair logic — keep them off.
    if (x>hh.cx-1.6 && x<hh.cx+1.6 && z>=hh.cz+hd && z<hh.cz+hd+7.5) return true;
  }catch(e){}
  return false;
}

/* ---------------- glitch dispatch ----------------
   Every NPC is a QA tester. problem = what went wrong; what = what it was
   doing (state); why = its intent. Newest 50 kept. */
/* npcGlitch(n, problem, what, why) — files one NPC QA dispatch call: who
   (NPC#id + type), where (rounded x,z), what they were doing (state), why
   (intent), and what went wrong. Keeps the newest 50; forces the next report
   tick (repT=0) so the Report panel shows it promptly. Joshua reads these
   as his live geometry audit. */
function npcGlitch(n, problem, what, why){
  glitchTotal++;
  try{
    glitchLog.push({
      caller: 'NPC#'+n.id+' ('+TYPE_NAMES[n.type]+')',
      location: [+n.x.toFixed(1), +n.z.toFixed(1)],
      what: what || STATE_NAMES[n.state],
      why: why || 'deciding where to go',
      problem: problem,
      t: new Date().toISOString()
    });
    if (glitchLog.length>50) glitchLog.splice(0, glitchLog.length-50);
    repT=0;   // publish on the next frame
  }catch(e){}
}

/* ---------------- spawn placement (deterministic) ---------------- */
/* collectSpots() — builds the three spawn pools once: walkRoads (non-highway
   roads only — nobody spawns on I-20/85/75/285), comSpots (OSM type 1/2 =
   commercial/apartment), resSpots (PLACED_HOUSES). Called once at init. */
function collectSpots(){
  walkRoads=[]; comSpots=[]; resSpots=[];
  try{
    if (typeof roadDrawData!=='undefined' && roadDrawData)
      for (var i=0;i<roadDrawData.length;i++){
        var r=roadDrawData[i];
        // no pedestrians spawning on highways (I-20/85/75/285)
        if (r && r.pts && r.pts.length>=2 && r.cat!=='highway') walkRoads.push(r);
      }
  }catch(e){}
  try{
    // OSM types: 0 house, 1 commercial, 2 apartment/large, 3 other
    if (typeof OSM_BUILDINGS!=='undefined' && OSM_BUILDINGS)
      for (var j=0;j<OSM_BUILDINGS.length;j++){
        var b=OSM_BUILDINGS[j];
        if (b && (b[5]===1||b[5]===2)) comSpots.push(b);
      }
  }catch(e){}
  try{
    if (typeof PLACED_HOUSES!=='undefined' && PLACED_HOUSES)
      for (var k=0;k<PLACED_HOUSES.length;k++) resSpots.push(PLACED_HOUSES[k]);
  }catch(e){}
}
/* roadsideSpot() — random point along a random non-highway road, offset
   perpendicular (half-width + 2.5-5.5u, random side) so the spawn is OFF the
   asphalt — pedestrians start on the shoulder/grass, never in traffic. */
function roadsideSpot(){
  var r=walkRoads[(srand()*walkRoads.length)|0];
  var pts=r.pts, si=(srand()*(pts.length-1))|0;
  var a=pts[si], b=pts[si+1], t=srand();
  var x=a[0]+(b[0]-a[0])*t, z=a[1]+(b[1]-a[1])*t;
  var dx=b[0]-a[0], dz=b[1]-a[1], L=Math.hypot(dx,dz)||1;
  var side=srand()<0.5?1:-1, off=r.w/2+2.5+srand()*3;   // off the asphalt
  return [x+(-dz/L)*off*side, z+(dx/L)*off*side];
}
/* nearSpot(list, isOSM) — random point on a ring around a building
   (half the building's footprint + 3-9u out): "near the building" without
   being inside it. isOSM picks the OSM [x,z,w,d,...] layout vs the
   PLACED_HOUSES [x,z,w,d] layout. */
function nearSpot(list, isOSM){
  var s=list[(srand()*list.length)|0];
  var w=isOSM?s[2]:s[2], d=isOSM?s[3]:s[3];
  var ang=srand()*Math.PI*2, dist=Math.max(w,d)/2+3+srand()*6;
  return [s[0]+Math.cos(ang)*dist, s[1]+Math.sin(ang)*dist];
}
/* spawnNPC(id) — creates one NPC data object: up to 12 placement tries
   (55% roadside / 20% commercial / 25% residential, falling back to roadside
   when a pool is empty; [4000,6000] is the last-resort map middle), then
   type by roll (45% man / 40% woman / 15% boy16 — Joshua's age rule: nobody
   under 16, nobody over 65), walk speed by type (boys fastest: 1.6-2.1 u/s),
   0.85 body scale for boys, 3 random body-width variants, and randomized
   skin (brown tones per spec)/shirt/pants. Speeds use srand (stable) at
   spawn; AI uses Math.random per frame. */
function spawnNPC(id){
  var pt=null, tries=0, roll=srand();
  // 55% roadside / 20% commercial / 25% residential (fall back to roadside)
  while (tries<12){
    if (roll<0.55 || (roll<0.75 && !comSpots.length) || (roll>=0.75 && !resSpots.length)){
      if (walkRoads.length) pt=roadsideSpot();
    } else if (roll<0.75){
      pt=nearSpot(comSpots,true);
    } else {
      pt=nearSpot(resSpots,false);
    }
    if (!pt){ pt=[4000,6000]; break; }                 // last-resort map middle
    if (!npcBlocked(pt[0],pt[1])) break;              // good spot
    tries++;
  }
  var tr=srand();
  var type= tr<0.45?0 : (tr<0.85?1:2);                 // 45% men / 40% women / 15% boys
  var n={
    id:id, x:pt[0], z:pt[1], heading:srand()*Math.PI*2,
    state: srand()<0.7?ST_WALK:ST_IDLE,
    stateT: 1+srand()*4, speed: 0, seed: srand(), type: type,
    y:0, phase:srand()*6.28, walkAmt:0, slot:-1,
    lx:pt[0], lz:pt[1], stuckT:0, fails:0, _pick:false,
    scl:  type===2?0.85:1.0,                          // 16yo boys: 0.85 scale
    wid:  type===2?0.9:[0.9,1.0,1.18][(srand()*3)|0],  // 3 body-type widths
    skin: SKINS[(srand()*SKINS.length)|0],
    shirt:SHIRTS[(srand()*SHIRTS.length)|0],
    pants:PANTS[(srand()*PANTS.length)|0],
    /* v1.17 transit commuter fields (Joshua's citizen rule): commuter 0 =
       wanderer, 1 = bus commuter, 2 = train commuter. transit = target
       {kind,stop|station...}, goto = walk target {x,z}, waiting = standing
       at the stop, boarding = {kind,ref} vehicle being boarded. lockY pins
       the render height (train platforms are elevated). */
    commuter: (function(){ var r=srand(); return r<TR_BUS_R?1:(r<TR_BUS_R+TR_TRAIN_R?2:0); })(),
    transit:null, goto:null, gotoT:0, waiting:false, waitT:0,
    boarding:null, boardT:0, commT:0, lockY:false
  };
  n.speed = type===0 ? 1.3+srand()*0.4 : type===1 ? 1.2+srand()*0.4 : 1.6+srand()*0.5;
  try{ n.y=(typeof clampVehY==='function')?clampVehY(n.x,n.z,groundRefY(n.x,n.z)):groundRefY(n.x,n.z); }catch(e){ n.y=0; }
  n.lx=n.x; n.lz=n.z;
  return n;
}

/* ---------------- free-think AI ----------------
   No waypoints, no pathfinding. WALK a heading for a few seconds, IDLE and
   look around, TURN to a new heading. Sample ahead; if blocked, TURN.
   PERF trick: the lookahead probe and stuck check are staggered per NPC
   ((npcTick+n.id)%18 and %60) so only ~1/18th of the population probes per
   frame — 1000 NPCs × probes every frame would be too slow on the TCL. */
/* aiNPC(n, dt) — one AI tick:
     WALK: advance along heading; every ~0.3s probe 3.2u ahead and TURN if
       blocked; every ~1s check displacement (moved <0.6u while walking =
       stuck): after 5s file a glitch and TURN; unexpected deep water also
       files a glitch. Timer end → 35% IDLE, else TURN.
     IDLE: gentle sinusoidal heading wander (look around), no position drift.
     TURN: pick a random new heading, probe it; walk it if clear, else retry —
       after 10 failed turns file a glitch and walk anyway (the stuck
       detector watches; better to keep moving than spin forever). */
/* setState(n, st, t) — sets the NPC's AI state and its countdown timer. */
function setState(n, st, t){ n.state=st; n.stateT=t; }
function aiNPC(n, dt){
  /* v1.14: conversation focus — the NPC is facing the player for a chat.
     Pause the wander AI (no walking off, no state-timer expiry) while
     npcFaceTick eases the heading toward the player. */
  if (n.focus){ n.stateT=Math.max(n.stateT,0.5); return; }
  /* v1.17 transit boarding — walk to the dwelling vehicle and get on.
     boarding = {kind:'bus'|'train', ref: vehicle record}. If the vehicle
     leaves before the NPC reaches it, go back to waiting for the next one.
     Within 3u of the vehicle = boarded: the NPC "rides away" and respawns
     elsewhere in the world. */
  if (n.boarding){
    var stillDw=false, bvx=0, bvz=0;
    try{ var _br=n.boarding.ref; stillDw=(_br.state==='dwell'); bvx=_br.x; bvz=_br.z; }catch(e){}
    if (!stillDw){  // missed it — back to waiting for the next one
      n.boarding=null; n.waiting=true; n.waitT=TR_WAIT_T; setState(n,ST_IDLE,1e9); return;
    }
    var bdx=bvx-n.x, bdz=bvz-n.z, bd=Math.hypot(bdx,bdz);
    if (bd<3){ npcRespawn(n); return; }   // boarded — rode away
    n.boardT-=dt;
    if (n.boardT<=0){ n.boarding=null; n.waiting=true; n.waitT=TR_WAIT_T; setState(n,ST_IDLE,1e9); return; }
    n.heading=Math.atan2(bdx,bdz); n.state=ST_WALK;
    var bstep=n.speed*dt, bnx=n.x+Math.sin(n.heading)*bstep, bnz=n.z+Math.cos(n.heading)*bstep;
    if (!npcBlocked(bnx,bnz,n)){ n.x=bnx; n.z=bnz; separateNPC(n); separateFromPlayer(n); if(!n.lockY){ try{n.y=groundRefY(n.x,n.z);}catch(e){} } }
    return;
  }
  /* v1.17 walking to a transit stop/station (n.goto = {x,z}). Steers straight
     at the target with sidestep probes around blockages (same probe the
     free-think AI uses). On arrival: settle into the waiting spot and WAIT.
     Times out after TR_GOTO_T and reverts to wandering. */
  if (n.goto){
    n.gotoT-=dt;
    var gdx=n.goto.x-n.x, gdz=n.goto.z-n.z, gd=Math.hypot(gdx,gdz);
    if (gd<TR_ARRIVE_R || n.gotoT<=0){
      if (gd<TR_ARRIVE_R){
        n.goto=null;
        if (n.transit&&n.transit.kind==='train') settleAtStation(n); else settleAtStop(n);
        n.waiting=true; n.waitT=TR_WAIT_T; setState(n,ST_IDLE,1e9);
      } else {  // couldn't reach it — wander instead
        n.goto=null; n.transit=null; setState(n,ST_TURN,0);
      }
      return;
    }
    n.heading=Math.atan2(gdx,gdz); n.state=ST_WALK;
    var gstep=n.speed*dt, gnx=n.x+Math.sin(n.heading)*gstep, gnz=n.z+Math.cos(n.heading)*gstep;
    if (!npcBlocked(gnx,gnz,n)){ n.x=gnx; n.z=gnz; separateNPC(n); separateFromPlayer(n); try{n.y=groundRefY(n.x,n.z);}catch(e){} }
    else {
      var gok=false;
      for (var ga=0;ga<4&&!gok;ga++){
        var ha=n.heading+((ga%2)?1:-1)*(0.6+0.5*((ga/2)|0));
        var tx2=n.x+Math.sin(ha)*gstep, tz2=n.z+Math.cos(ha)*gstep;
        if (!npcBlocked(tx2,tz2,n)){ n.x=tx2; n.z=tz2; separateNPC(n); separateFromPlayer(n); gok=true; }
      }
      if (!gok){
        n.stuckT=(n.stuckT||0)+dt;
        if (n.stuckT>4){ npcGlitch(n,'cannot reach transit stop','GOTO','walking to bus stop'); n.stuckT=0; n.goto=null; n.transit=null; setState(n,ST_TURN,0); }
      }
    }
    return;
  }
  /* v1.17 waiting at a stop/station — stand, look around, never wander off.
     Joshua's rule: bus riders stand AT the bus stop; train riders on the
     platform. Gives up after TR_WAIT_T and wanders. */
  if (n.waiting){
    n.heading+=Math.sin(npcTick*0.05+n.seed*6.283)*0.4*dt;  // look around
    n.waitT-=dt;
    if (n.waitT<=0){ n.waiting=false; n.transit=null; n.lockY=false; setState(n,ST_TURN,0); }
    return;
  }
  n.stateT-=dt;
  if (n.state===ST_WALK){
    var step=n.speed*dt;
    n.x+=Math.sin(n.heading)*step;
    n.z+=Math.cos(n.heading)*step;
    separateNPC(n); separateFromPlayer(n);   // v1.20/1.21: never overlap another NPC or the player
    // staggered lookahead probe (~every 0.3s per NPC at 60fps)
    if ( ((npcTick+n.id)%18)===0 ){
      var px=n.x+Math.sin(n.heading)*3.2, pz=n.z+Math.cos(n.heading)*3.2;
      if (npcBlocked(px,pz,n) || npcNearOther(px,pz,1.6)){ n.fails++; setState(n,ST_TURN,0); }
    }
    // staggered stuck check (~every 1s): moved <0.6u while walking = stuck
    if ( ((npcTick+n.id)%60)===0 ){
      var dx=n.x-n.lx, dz=n.z-n.lz;
      if (dx*dx+dz*dz < 0.36){ n.stuckT++; } else { n.stuckT=0; }
      n.lx=n.x; n.lz=n.z;
      if (n.stuckT>=5){
        npcGlitch(n,'stuck on geometry for >5s','WALK','heading somewhere');
        n.stuckT=0; n.fails=0; setState(n,ST_TURN,0);
      }
      // deep water should never happen (probes avoid it) — report if it does
      try{
        if (typeof waterDepthAt==='function' && waterDepthAt(n.x,n.z)>1.2){
          npcGlitch(n,'entered deep water unexpectedly','WALK','heading somewhere');
          setState(n,ST_TURN,0);
        }
      }catch(e){}
    }
    if (n.stateT<=0){
      if (Math.random()<0.35) setState(n,ST_IDLE,1+Math.random()*2);  // pause, look around
      else setState(n,ST_TURN,0);
    }
  }
  else if (n.state===ST_IDLE){
    // "look around": gentle sinusoidal heading wander, no drift
    n.heading+=Math.sin(npcTick*0.05+n.seed*6.283)*0.4*dt;
    if (n.stateT<=0) setState(n,ST_TURN,0);
  }
  else { // ST_TURN: pick a heading, verify it, walk it — or try another
    n.heading+=(Math.random()*2-1)*2.4;
    var tx=n.x+Math.sin(n.heading)*3.2, tz=n.z+Math.cos(n.heading)*3.2;
    if (!npcBlocked(tx,tz,n) && !npcNearOther(tx,tz,1.6)){
      n.fails=0; setState(n,ST_WALK,2.5+Math.random()*3.5);
    } else {
      n.fails++;
      if (n.fails>10){
        npcGlitch(n,'blocked repeatedly ('+n.fails+' failed turns)','TURN',
                  'trying to find a walkable heading');
        n.fails=0; setState(n,ST_WALK,2);   // walk anyway; stuck-detector watches
      }
    }
  }
}

/* ---------------- streaming: bodies only near the camera ---------------- */
/* assignSlot(s,n) — binds NPC n to render slot s and bakes its per-instance
   colors: skin on head+arms (short-sleeve look), shirt on torso, pants on
   legs. Slot count is set to the visible count each frame; unassigned slots
   are never drawn. */
function assignSlot(s,n){
  n.slot=s; slots[s]=n;
  _col.set(n.skin);
  _mesh.head.setColorAt(s,_col); _mesh.armL.setColorAt(s,_col); _mesh.armR.setColorAt(s,_col);
  _col.set(n.shirt); _mesh.torso.setColorAt(s,_col);
  _col.set(n.pants); _mesh.legL.setColorAt(s,_col); _mesh.legR.setColorAt(s,_col);
  var mk=[_mesh.torso,_mesh.head,_mesh.armL,_mesh.armR,_mesh.legL,_mesh.legR];
  for (var i=0;i<mk.length;i++) if (mk[i].instanceColor) mk[i].instanceColor.needsUpdate=true;
}
/* refreshSlots(px,pz) — reassigns the 40 render slots every 0.5s: releases
   NPCs beyond HIDE_R (200u — hysteresis so bodies don't pop at the
   VISIBLE_R 150u boundary), then fills freed slots with the nearest
   unslotted NPCs inside VISIBLE_R. No allocation: a _pick flag on each NPC
   prevents double-picking within one pass, and _free is a reused scratch
   array. Note: the fill scan is O(slots × npcs) — acceptable at 0.5s
   cadence, would not be per frame. */
function refreshSlots(px,pz){
  var VR2=VISIBLE_R*VISIBLE_R, HR2=HIDE_R*HIDE_R, i, s, n;
  _free.length=0;
  for (s=0;s<MAX_VISIBLE;s++){
    n=slots[s];
    if (n){
      var dx=n.x-px, dz=n.z-pz;
      if (dx*dx+dz*dz>HR2){ n.slot=-1; slots[s]=null; _free.push(s); }
    } else _free.push(s);
  }
  // fill freed slots with the nearest unslotted NPCs (no allocation: flag scan)
  for (var f=0;f<_free.length;f++){
    var best=null, bestD=VR2;
    for (i=0;i<npcs.length;i++){
      n=npcs[i];
      if (n.slot>=0||n._pick) continue;
      var ex=n.x-px, ez=n.z-pz, d2=ex*ex+ez*ez;
      if (d2<bestD){ bestD=d2; best=n; }
    }
    if (!best) break;
    best._pick=true; assignSlot(_free[f],best);
  }
  for (i=0;i<npcs.length;i++) npcs[i]._pick=false;
}

/* ---------------- rendering: 6 InstancedMeshes, ~6-10 boxes per NPC ----------------
   One unit box per part, scaled by matrix. Per-instance colors: skin on head
   + arms (short-sleeve look), shirt on torso, pants on legs. Boys render at
   0.85 scale; 3 width variants via wid. */
/* partMat(...) — composes one body-part's matrix from 7 premultiplied
   matrices: world translate → yaw → body scale → part offset → limb swing
   (rotation X) → pivot drop → part size. All scratch matrices are allocated
   once at init (never in the hot loop); _out is returned. */
function partMat(wx,wy,wz,yaw,scl, px,py,pz, swing,drop, sx,sy,sz){
  _m1.makeTranslation(wx,wy,wz);
  _m2.makeRotationY(yaw);
  _m3.makeScale(scl,scl,scl);
  _m4.makeTranslation(px,py,pz);
  _m5.makeRotationX(swing);
  _m6.makeTranslation(0,drop,0);
  _m7.makeScale(sx,sy,sz);
  return _out.copy(_m1).multiply(_m2).multiply(_m3)
              .multiply(_m4).multiply(_m5).multiply(_m6).multiply(_m7);
}
/* renderNPCs(dt,px,pz) — writes body-part matrices for every slotted NPC.
   walkAmt eases toward 1 (walking) / 0 (idle) so limbs don't snap; the walk
   phase advances at 3.2+speed*2.6 rad/s; legs swing opposed (sw / -sw),
   arms counter-swing (asw / -asw); distant NPCs get a static pose
   (ANIM_R=80u LOD — animation only near the camera). A non-finite terrain
   height is reported as a "fell through world" glitch and clamped to the
   last good height. */
function renderNPCs(dt,px,pz){
  var s, n, vis=0, AR2=ANIM_R*ANIM_R;
  for (s=0;s<MAX_VISIBLE;s++){
    n=slots[s]; if(!n) continue;
    vis++;
    var dx=n.x-px, dz=n.z-pz, near=(dx*dx+dz*dz)<AR2;
    /* v1.17: lockY pins the render height for train-platform waiters
       (platforms are elevated; heightAt would drop them to the ground). */
    var y; try{ y = n.lockY ? n.y : heightAt(n.x,n.z); }catch(e){ y=NaN; }
    if (!isFinite(y)){
      npcGlitch(n,'fell through world','WALK','standing on terrain');
      y=isFinite(n.y)?n.y:0;
    }
    if (typeof clampVehY==='function') y=clampVehY(n.x,n.z,y);  // v1.12: ground clamp — no sky-floaters
    n.y=y;
    var target=(n.state===ST_WALK)?1:0;
    n.walkAmt+=(target-n.walkAmt)*Math.min(1,6*dt);
    if (near && n.walkAmt>0.02) n.phase+=dt*(3.2+n.speed*2.6)*n.walkAmt;
    var sw=Math.sin(n.phase)*0.55*n.walkAmt;       // legs oppose...
    var asw=Math.sin(n.phase)*0.45*n.walkAmt;      // ...arms counter-swing
    if (!near){ sw=0; asw=0; }                    // distant: static pose
    var scl=n.scl, yaw=n.heading, wid=n.wid;
    _mesh.torso.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, 0,1.075,0, 0,0, 0.42*wid,0.55,0.26*wid));
    _mesh.head.setMatrixAt (s, partMat(n.x,y,n.z,yaw,scl, 0,1.49,0,  0,0, 0.24,0.28,0.24));
    _mesh.armL.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, -0.265*wid,1.28,0, -asw,-0.29, 0.11,0.58,0.11));
    _mesh.armR.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl,  0.265*wid,1.28,0,  asw,-0.29, 0.11,0.58,0.11));
    _mesh.legL.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, -0.115*wid,0.80,0,  sw,-0.33, 0.15,0.66,0.15));
    _mesh.legR.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl,  0.115*wid,0.80,0, -sw,-0.33, 0.15,0.66,0.15));
  }
  visCount=vis;
  var mk=[_mesh.torso,_mesh.head,_mesh.armL,_mesh.armR,_mesh.legL,_mesh.legR];
  for (var i=0;i<mk.length;i++){ mk[i].count=vis; mk[i].instanceMatrix.needsUpdate=true; }
}

/* publishReport() — pushes the NPC status to the Report panel every 5s:
   population, visible count, and the live glitch log (Joshua's NPC QA
   dispatch calls). Guarded — safe when Report isn't loaded. */
function publishReport(){
  try{
    if (typeof Report!=='undefined' && Report.setSys){
      Report.setSys('npc',{
        count:npcs.length, visible:visCount, maxVisible:MAX_VISIBLE,
        glitchReports:glitchLog.slice(), glitchTotal:glitchTotal,
        note:'free-think pedestrians (WALK/IDLE/TURN, no waypoints); bodies stream in under 150u'
      });
    }
  }catch(e){}
}

/* ---------------- init ---------------- */
/* initNPCs() — allocates scratch matrices, builds the border, fills spawn
   pools, creates all 1000 NPCs, the 40 render slots, and the 6
   InstancedMeshes (one per body part, unit-box geometry scaled per part).
   Meshes are frustumCulled=false (positions update every frame; culling the
   batch would hide everyone) with cast/receive shadows off for perf. */
function initNPCs(){
  try{ buildNpcColGrid(); }catch(e){}   // v1.20: static collider grid (trees/signs/poles)
  _m1=new THREE.Matrix4(); _m2=new THREE.Matrix4(); _m3=new THREE.Matrix4();
  _m4=new THREE.Matrix4(); _m5=new THREE.Matrix4(); _m6=new THREE.Matrix4();
  _m7=new THREE.Matrix4(); _out=new THREE.Matrix4();
  _col=new THREE.Color();
  buildBorder();
  collectSpots();
  for (var i=0;i<NPC_COUNT;i++) npcs.push(spawnNPC(i));
  for (var s=0;s<MAX_VISIBLE;s++) slots.push(null);
  var unitBox=new THREE.BoxGeometry(1,1,1);
  function im(){
    var m=new THREE.InstancedMesh(unitBox,
      new THREE.MeshLambertMaterial({color:0xffffff}), MAX_VISIBLE);
    m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
    m.frustumCulled=false;      // positions update every frame; never cull the batch
    m.castShadow=false; m.receiveShadow=false;
    m.count=0; scene.add(m); return m;
  }
  _mesh={ torso:im(), head:im(), armL:im(), armR:im(), legL:im(), legR:im() };
  /* v1.21 NPC KILL SWITCH: register meshes globally so __setNpcPaused can
     hide/show them instantly without touching the NPC data. */
  try {
    window.__npcMeshes=[_mesh.torso,_mesh.head,_mesh.armL,_mesh.armR,_mesh.legL,_mesh.legR];
    if (window.__npcPaused) for (var _hi=0; _hi<window.__npcMeshes.length; _hi++) window.__npcMeshes[_hi].visible=false;
  } catch(e){}
  npcReady=true;
  publishReport();
}

/* tryInit() — waits for the main script's world (THREE, scene,
   roadDrawData) to exist, then inits once. ~20s grace (40 × 500ms); after
   that the NPC system stays off and the game is unaffected. */
var initTries=0;
function tryInit(){
  try{
    if (typeof THREE==='undefined' || typeof scene==='undefined' ||
        typeof roadDrawData==='undefined' || !roadDrawData || !roadDrawData.length){
      if (++initTries<40) setTimeout(tryInit,500);   // ~20s grace
      return;
    }
    initNPCs();
  }catch(e){ /* NPC system stays off; game unaffected */ }
}

/* ---------------- NPC conversations (v1.14) ----------------
   JOSHUA'S DIRECTIVE (2026-10-09): NPCs that are NOT part of the work crew
   should talk about Atlanta. When the player walks up to one:
     1. the NPC turns to face the player,
     2. a TALK prompt appears on the universal action button
        (same pattern as ENTER CAR),
     3. tapping it opens a dialogue panel with a randomized Atlanta-themed
        line — Zoo, Aquarium, Botanical Garden, Centennial Olympic Park,
        High Museum, Fox Theatre, Ponce City Market, BeltLine, Underground
        Atlanta, Stone Mountain, World of Coca-Cola, MARTA, restaurants,
        parks, neighborhoods, events.
   NOTE: every NPC in THIS file is a pedestrian — the road crew lives in
   roadcrew_system.js, so no crew-filtering is needed here.
   While an NPC has "focus" (player nearby) it pauses its wander AI and
   eases its heading toward the player. The dialogue panel is owned by
   index.html (showNpcDialog/hideNpcDialog); this module only supplies the
   lines and the proximity/talk state. */
/* TALK_LINES — the Atlanta conversation pool. First-person, casual, PG.
   ~64 unique lines across the categories Joshua named. */
/* ============================================================================
   NPC DIALOGUE DATABASE (v1.14.1) — NPC Dialogue Director's domain.
   ----------------------------------------------------------------------------
   Joshua's directive (2026-10-09): NPCs that are NOT part of the work crew
   talk about Atlanta — attractions, food, transit, neighborhoods, events.
   When the player walks up, the NPC turns to face them and a TALK prompt
   appears on the universal action button (same pattern as ENTER CAR).

   STRUCTURE: personality pools. Every NPC type (man / woman / boy16) gets
   its own voice plus a shared pool of general Atlanta lines. npcTalkLine(n)
   merges the NPC's pool with the shared pool and picks a random line —
   never the same line twice in a row (talkLastKey tracks pool+index).

   VOICE RULES (set by the Dialogue Director):
     - All lines first-person, casual, PG. Things a real Atlanta local
       would actually say out loud to a stranger on the sidewalk.
     - boy16 lines are age-appropriate: school, friends, games, sports —
       never bars, clubs, or adult nightlife.
     - No named real people. Places are fine (they're public landmarks).
   GROWTH: add new lines to the right pool; the picker needs no changes.
   ============================================================================ */
/* TALK_SHARED — general Atlanta lines any NPC can say. */
var TALK_SHARED=[
 /* --- Zoo Atlanta --- */
 "Have you checked out Zoo Atlanta yet? The pandas are something else.",
 "I just came from the zoo — the gorillas were putting on a show today.",
 "Zoo Atlanta's got that African savanna exhibit now, you gotta see it.",
 "Took my cousins to the zoo last weekend — they loved the giraffes.",
 "The reptile house at the zoo gives me the creeps, but it's cool.",
 /* --- Georgia Aquarium --- */
 "Have you been to the Georgia Aquarium yet? It's massive!",
 "The whale sharks at the aquarium — you won't believe how big they are.",
 "I just came from the aquarium downtown. That ocean tunnel is unreal.",
 "The dolphin show at the Georgia Aquarium is worth every penny.",
 "One of the biggest aquariums in the world and it's right here. Wild.",
 /* --- Atlanta Botanical Garden --- */
 "You been to the Atlanta Botanical Garden? Beautiful this time of year.",
 "The Garden's holiday lights are the best night out in the city.",
 "I was just over at the Botanical Garden. The orchid house smells amazing.",
 "The canopy walk at the Garden — you're walking through the treetops.",
 /* --- Centennial Olympic Park --- */
 "Centennial Olympic Park is where it's at on weekends.",
 "They still run the Fountain of Rings show at the park — kids love it.",
 "I just came from Centennial Park. Perfect day for it.",
 "The park was built for the '96 Olympics. Still the heart of downtown.",
 /* --- High Museum --- */
 "The High Museum has a new exhibit — thinking about going Saturday.",
 "Have you been to the High? That building alone is a work of art.",
 "The High's folk art collection is underrated. Go see it.",
 /* --- Fox Theatre --- */
 "Have you been to the Fox Theatre? Caught a show there last week.",
 "The Fox is the prettiest building in Atlanta. Fight me.",
 "They're doing a classic movie night at the Fox next month.",
 "That Moorish architecture on the Fox — nothing else like it.",
 /* --- Ponce City Market --- */
 "Have you tried the food at Ponce City Market? So many options.",
 "I was just up at Ponce City Market — the rooftop view is crazy.",
 "Skip the line, hit the food hall at Ponce early.",
 "Ponce used to be a Sears warehouse. Now look at it.",
 /* --- Atlanta BeltLine --- */
 "The BeltLine is perfect for walking — have you been?",
 "I just biked the whole Eastside Trail. Best free thing in Atlanta.",
 "BeltLine on a Sunday afternoon — that's the move.",
 "The art on the BeltLine changes all the time. Always something new.",
 /* --- Underground Atlanta --- */
 "I was just down at Underground Atlanta. Lots of history down there.",
 "Underground's been changing a lot lately — worth another look.",
 /* --- Stone Mountain --- */
 "Stone Mountain is worth the drive, especially for the laser show.",
 "Hiked up Stone Mountain this morning — the skyline view is unreal.",
 "The train around Stone Mountain is a whole vibe.",
 /* --- World of Coca-Cola --- */
 "The World of Coca-Cola is a must-see if you haven't been.",
 "You can taste like a hundred sodas from around the world at Coca-Cola. Wild.",
 "Coke was invented right here in Atlanta. That's our thing.",
 /* --- MARTA --- */
 "Have you ridden MARTA to the airport? So convenient.",
 "The train to the airport beats sitting in Connector traffic any day.",
 "MARTA's got its problems, but the Gold Line gets me downtown fast.",
 "Pro tip: the airport station is right inside the terminal. Can't miss it.",
 /* --- Getting around --- */
 "Avoid the Downtown Connector at rush hour. Trust me on this.",
 "285 is a parking lot after 4. Plan accordingly.",
 "It rained for ten minutes and everybody forgot how to drive.",
 "Atlanta weather — wait five minutes, it'll change.",
 "The Perimeter is where the real traffic lives.",
 /* --- General Atlanta --- */
 "You new around here? Welcome to the A.",
 "This heat? Yeah, it's always like this. You'll get used to it.",
 "Have you seen the skyline at night from the Westside? Beautiful.",
 "Mercedes-Benz Stadium looks like a spaceship landed downtown.",
 "Have you been out to the Chattahoochee? Good fishing out there.",
 "Atlanta's a city in a forest. Look up — trees everywhere.",
 "The King Center downtown — everybody should visit at least once.",
 "Oakland Cemetery does tours — spooky and historic.",
 "The Center for Civil Rights downtown — powerful stuff."
];
/* TALK_MAN — adult men's pool: sports, work commute, local history. */
var TALK_MAN=[
 "Did you catch the Braves game? This city's buzzing.",
 "Falcons better get it together this season, I'm saying.",
 "Hawks are fun to watch this year. State Farm Arena gets loud.",
 "Atlanta United matches — the atmosphere is unreal. Best fans in MLS.",
 "I remember when the Braves were at Turner Field. Times change.",
 "Dragon Con takes over downtown every year — it's wild.",
 "Have you toured the CNN Center? Right by the park.",
 "Sweet Auburn — that's where Atlanta's Black history lives. Go walk it.",
 "The Varsity — been going since I was a kid. Chili dogs never miss.",
 "Best lemon pepper wings in the city? Don't even get me started.",
 "I drive the Connector every morning. Pray for me.",
 "You ever been stuck on 75/85 when it shuts down? Nightmare.",
 "They finally fixed that pothole on Cascade. Only took a year.",
 "My commute's twenty minutes unless 285 says otherwise.",
 "Adamsville's home. Been here my whole life.",
 "East Point's got that old-school Atlanta feel.",
 "Buckhead's fancy, but the real Atlanta's down here.",
 "I grew up going to Adams Park. Still play ball there sometimes.",
 "Wilson Mill Park — good spot to clear your head.",
 "You know they filmed half of Hollywood out here now? Tyler Perry Studios and all.",
 "The old GM plant in Doraville — my uncle worked there thirty years.",
 "Fulton Industrial at night — nothing but trucks and streetlights.",
 "Have you had real soul food on Cascade? Life-changing.",
 "Go to The Beautiful for breakfast. Trust me on this one.",
 "Sweet tea here hits different. It's basically the city drink."
];
/* TALK_WOMAN — adult women's pool: community, food, parks, culture. */
var TALK_WOMAN=[
 "Piedmont Park on a Saturday — everybody's out there.",
 "Grant Park is underrated. The historic homes around it are gorgeous.",
 "Have you walked the trails at Cascade Springs? Real peaceful.",
 "The farmers market in East Point on Saturdays — fresh everything.",
 "Have you been to the High Museum's Friday jazz nights? So nice.",
 "Little Five Points is... an experience. Go see for yourself.",
 "Have you been down to Castleberry Hill? The art scene is blowing up.",
 "The Fox Theatre's Mighty Mo organ — they still play it before shows.",
 "I take my niece to the Children's Museum downtown. She loves it.",
 "The Center for Puppetry Arts — sounds silly, it's actually wonderful.",
 "Have you tried the food trucks at the park? The lines move fast.",
 "Real talk — the best peach cobbler is at my church's bake sale.",
 "You gotta try the Varsity — it's an Atlanta institution.",
 "Mary Mac's Tea Room — classic Atlanta comfort food.",
 "The BeltLine's Eastside Trail is my morning walk. Every morning.",
 "Chastain Park concerts in the summer — bring a picnic.",
 "Have you seen the Swan House? It's like a movie set.",
 "The MLK historic district — take the whole tour, not just the house.",
 "I just came from Trader Joe's on Piedmont. That parking lot is a war zone.",
 "Lenox on a Saturday — I don't know why I do this to myself.",
 "The aquarium's sleepovers for kids — mine still talks about it.",
 "Zoo Atlanta's behind-the-scenes tour — worth saving up for.",
 "Have you been to the Alliance Theatre? Great shows.",
 "The Wren's Nest in West End — storytelling at its finest."
];
/* TALK_BOY16 — 16-year-old boys: school, friends, sports, games. PG, age-fit. */
var TALK_BOY16=[
 "You go to school around here? I'm at Harper Archer.",
 "Man, practice ran long today. Coach is killing us.",
 "Have you been to the skate park yet? It's decent.",
 "We hoop at Adams Park after school. Pull up sometime.",
 "The new Spider-Man game? I've been grinding all week.",
 "You play 2K? I'm nice with the Hawks, no cap.",
 "Madden with the Falcons — we rebuilding, but it's fun.",
 "Have you been to a Braves game? Truist Park is electric.",
 "I wanna catch Atlanta United live one day. The tifo looks crazy.",
 "The aquarium field trip was actually fire, not gonna lie.",
 "Zoo Atlanta with the school — the lions were active that day.",
 "Have you walked the BeltLine? Me and my boys bike it.",
 "Centennial Park after school — everybody be out there.",
 "The Chick-fil-A on Cascade — that's the after-school spot.",
 "You tried the lemon pepper wings from J.R. Crickets? Elite.",
 "American Deli wings hit different after practice.",
 "MARTA to Five Points then walk to the park — easy day.",
 "The train to the airport just to ride it — we've all done it.",
 "My mom says stay off 285 on foot. Obviously.",
 "Have you seen the new sneakers at the mall? I need those.",
 "Six Flags over Georgia — the Goliath is still the best ride.",
 "White Water in the summer — that's the move.",
 "Stone Mountain laser show with the family — classic.",
 "The High Museum has student days. Art's actually kind of cool."
];
/* ============================================================================
   v1.22 CONTEXT-AWARE TALK (Joshua 2026-10-10): commuters WAITING at a stop
   or station talk about THAT — not generic city chatter. npcTalkLine() checks
   n.waiting + n.commuter first and serves from these pools before falling
   back to the personality pools. All lines first-person, casual, PG —
   things a real rider would say while waiting. No named real people.
   ============================================================================ */
/* TALK_WAITBUS — bus commuters standing at a stop. */
var TALK_WAITBUS=[
 "Bus is running late again. Story of my life.",
 "You waiting on the bus too? This one is always late.",
 "I catch this bus every morning. Never on time, but it gets me there.",
 "Headed downtown. You know how long the ride is from here?",
 "I just missed the last one. Now I'm stuck waiting.",
 "This stop is the only one that gets me to work on time. Usually.",
 "MARTA bus — love it or hate it, it's my ride.",
 "Waiting on my bus. You'd think they'd add more by now.",
 "I got my transfer ready. This driver's cool, he waits if he sees you running.",
 "Going to meet my sister. Bus is cheaper than gas these days.",
 "I ride this route every day. I know all the drivers by name.",
 "Hope this bus has AC. Last one was a sauna on wheels.",
 "Going to work. This bus gets me there if traffic behaves.",
 "I take the bus so I don't have to fight for parking.",
 "Ever tried to catch the bus in the rain? Not fun.",
 "My stop's coming up after about ten more. Long ride."
];
/* TALK_WAITTRAIN — train commuters standing on a station platform. */
var TALK_WAITTRAIN=[
 "Train's coming. I can feel it in the rails.",
 "Gold Line downtown — fastest way through the city.",
 "I ride to Five Points every morning for work.",
 "You ever ridden to the airport? Station's right in the terminal.",
 "This platform gets packed at rush hour. Get here early.",
 "Red Line, Gold Line — I mix them up every time.",
 "The train beats sitting in Connector traffic. Every time.",
 "Headed to the airport to pick up my cousin.",
 "I love the train at night. City lights the whole way.",
 "I take the train so I don't have to fight for parking downtown.",
 "Next stop's mine. Well — after about six more stops.",
 "Going to work. Train gets me there faster than driving.",
 "The train to the airport beats sitting in traffic any day.",
 "I ride this line every day. Best seat is by the window.",
 "They keep the platform clean here. I appreciate that.",
 "Almost missed it last time — the doors close fast."
];
/* TALK_LINES — legacy combined pool, kept for the inspector/debug rig.
   The live picker (npcTalkLine) uses the personality pools above. */
var TALK_LINES=TALK_SHARED.concat(TALK_MAN,TALK_WOMAN,TALK_BOY16);
var TALK_R=4.5;        // TALK prompt range (units) — matches ENTER CAR's 4.5u
var TALK_FACE_R=8;     // NPC turns to face the player inside this range
var TALK_END_R=6;      // conversation auto-ends beyond this range
var talkNPC=null;      // NPC currently in conversation (data object or null)
var talkLastIdx=-1;    // index of the last line spoken — never repeat twice in a row
/* npcTalkLine(n) — picks a random line for NPC n from its personality pool
   (TALK_MAN / TALK_WOMAN / TALK_BOY16) merged with TALK_SHARED — never the
   same pool+index twice in a row (talkLastKey tracks "pool:index"). Falls
   back to the combined TALK_LINES if the NPC type is unreadable. The guard
   loop caps at 10 tries; pools are 70+ lines each, so a repeat is only
   possible on pathological RNG. */
var talkLastKey='';
function npcTalkPool(n){
  /* type: 0=man, 1=woman, 2=boy16 (see TYPE_NAMES). Unknown -> shared only. */
  try{
    if (n && n.type===0) return {name:'man',  lines:TALK_MAN.concat(TALK_SHARED)};
    if (n && n.type===1) return {name:'woman',lines:TALK_WOMAN.concat(TALK_SHARED)};
    if (n && n.type===2) return {name:'boy',  lines:TALK_BOY16.concat(TALK_SHARED)};
  }catch(e){}
  return {name:'all', lines:TALK_LINES};
}
function npcTalkLine(n){
  /* v1.22 context-aware (Joshua 2026-10-10): a commuter WAITING at a stop or
     station talks about that — bus riders get the bus pool, train riders on
     the platform get the train pool. Falls through to personality pools for
     everyone else (wanderers, commuters still walking to their stop).
     talkPickFresh() keeps the never-repeat-twice rule for every pool. */
  try{
    if (n && n.waiting){
      if (n.commuter===2 && typeof TALK_WAITTRAIN!=='undefined' && TALK_WAITTRAIN.length)
        return talkPickFresh('waittrain', TALK_WAITTRAIN);
      if (n.commuter===1 && typeof TALK_WAITBUS!=='undefined' && TALK_WAITBUS.length)
        return talkPickFresh('waitbus', TALK_WAITBUS);
    }
  }catch(e){}
  var pool=npcTalkPool(n);
  return talkPickFresh(pool.name, pool.lines);
}
/* talkPickFresh(poolName, lines) — picks a random line from the given pool,
   never the same pool+index twice in a row (talkLastKey). Shared by the
   context-aware picker above and the personality picker. */
function talkPickFresh(poolName, lines){
  var i, guard=0, key;
  do {
    i=(Math.random()*lines.length)|0; guard++;
    key=poolName+':'+i;
  } while (key===talkLastKey && guard<10);
  talkLastKey=key;
  return lines[i];
}
/* npcDisplayName(n) — the speaker label shown in the dialogue panel.
   Kept generic per Joshua's spec (no named characters yet). */
function npcDisplayName(n){
  try{ return n.type===2 ? 'LOCAL TEEN' : 'ATLANTA LOCAL'; }catch(e){ return 'ATLANTA LOCAL'; }
}
/* npcTalkEligible() — true only when the player is on foot and outside.
   No TALK prompt while driving, inside a building, or riding transit.
   All reads are guarded: a missing global degrades to "not eligible". */
function npcTalkEligible(){
  try{
    if (typeof car!=='undefined' && car && car.driving) return false;
    if (typeof player!=='undefined' && player &&
        (player.inside || player.ridingTrain || player.ridingBus)) return false;
  }catch(e){}
  return true;
}
/* npcTalkNearest(px,pz) — nearest VISIBLE (slotted) NPC within TALK_R of
   (px,pz), or null. Only slotted NPCs have bodies on screen, so the player
   can only meaningfully talk to those. Called every frame from the game's
   updateActionButton() — the slotted scan is tiny (<=40), never the full
   population. */
function npcTalkNearest(px,pz){
  if (!npcReady || !npcTalkEligible()) return null;
  var best=null, bd=TALK_R*TALK_R;
  try{
    for (var s=0;s<MAX_VISIBLE;s++){
      var n=slots[s]; if(!n) continue;
      var dx=px-n.x, dz=pz-n.z, d2=dx*dx+dz*dz;
      if (d2<bd){ bd=d2; best=n; }
    }
  }catch(e){ return null; }
  return best;
}
/* npcFaceTick(dt,px,pz) — runs inside updateNPCs each frame. Every NPC
   within TALK_FACE_R eases its heading toward the player ("turns to the
   individual", Joshua's words) and gets n.focus=true, which pauses its
   wander AI (see aiNPC). Leaving the radius clears focus and AI resumes.
   Also ends the active conversation if the player walks beyond TALK_END_R. */
function npcFaceTick(dt,px,pz){
  if (!npcReady) return;
  var eligible=npcTalkEligible();
  var FR2=TALK_FACE_R*TALK_FACE_R;
  try{
    for (var i=0;i<npcs.length;i++){
      var n=npcs[i];
      var dx=px-n.x, dz=pz-n.z, d2=dx*dx+dz*dz;
      if (eligible && d2<FR2){
        var want=Math.atan2(dx,dz);   // heading convention: 0 = +z (see aiNPC)
        var diff=want-n.heading;
        while (diff>Math.PI) diff-=Math.PI*2;
        while (diff<-Math.PI) diff+=Math.PI*2;
        n.heading+=diff*Math.min(1,10*dt);   // quick ease, no snap
        n.focus=true;
      } else if (n.focus){ n.focus=false; }
    }
    if (talkNPC){
      var tx=px-talkNPC.x, tz=pz-talkNPC.z;
      if (tx*tx+tz*tz > TALK_END_R*TALK_END_R){
        talkNPC.focus=false; talkNPC=null;
        try{ if (typeof hideNpcDialog==='function') hideNpcDialog(); }catch(e){}
      }
    }
  }catch(e){}
}
/* npcStartTalk(n) — begins (or continues) a conversation with NPC n.
   Locks focus so the NPC keeps facing the player while the panel is open.
   Tapping TALK again mid-conversation just serves a fresh line. */
function npcStartTalk(n){
  if (!n) return;
  try{
    talkNPC=n; n.focus=true;
    var line=npcTalkLine(n);
    if (typeof showNpcDialog==='function') showNpcDialog(npcDisplayName(n), line);
  }catch(e){}
}
/* npcEndTalk() — closes the conversation from the NPC side (panel close
   button calls hideNpcDialog directly; this clears the module state). */
function npcEndTalk(){
  try{ if (talkNPC) talkNPC.focus=false; }catch(e){}
  talkNPC=null;
}
window.npcTalkNearest=npcTalkNearest;
window.npcStartTalk=npcStartTalk;
window.npcEndTalk=npcEndTalk;
window.NPC_TALK_LINES=TALK_LINES;   // inspector/debug visibility

/* ---------------- NPC transit commuters (v1.17) ----------------
   JOSHUA'S CITIZEN RULE (2026-10-09): if a citizen is catching a bus, they
   MUST stand at a bus stop — the only exception is waiting at a train
   station for a train.

   How it works:
   - At spawn, ~22% of NPCs are bus commuters and ~6% train commuters
     (n.commuter: 0=wanderer, 1=bus, 2=train). The rest wander freely.
   - A staggered tick assigns each commuter the NEAREST stop/station once
     the transit systems have booted (MARTA_BUS / MARTA boot after NPCs, so
     assignment is lazy and guarded). Commuters whose system never boots
     revert to wanderers after ~90s.
   - The commuter walks to the stop/station (n.goto — straight-line steer
     with sidestep probes; see the v1.17 branches in aiNPC), then WAITS
     (n.waiting) standing at the stop — never in the road, never at a
     random spot. Bus riders settle just off the sign pole (shoulder);
     train riders step onto the platform deck (lockY pins their height).
   - When a bus/train DWELLS at that stop, waiting NPCs walk to the vehicle
     (n.boarding) and board: they despawn and respawn elsewhere, as if they
     rode to their destination. A vehicle that leaves early just means they
     wait for the next one.
   - window.npcWaitingStops() exposes the stops with waiting NPCs so the
     smart-stop system can skip empty stops (buses only stop where
     passengers wait). */
/* transitReady(kind) — true when the requested transit system has booted
   and published its stop/station list. 1=bus, 2=train. */
function transitReady(kind){
  try{
    if (kind===1){ var MB=window.MARTA_BUS; return !!(MB&&MB.ready&&MB.stops&&MB.stops.length); }
    if (kind===2){ var MT=window.MARTA; return !!(MT&&MT.ready&&MT.stations&&MT.stations.length); }
  }catch(e){}
  return false;
}
/* nearestBusStop(x,z) — closest MARTA bus stop object to (x,z), or null.
   The returned object is the LIVE stop record (identity matches the objects
   buses dwell at), so boarding can match by reference. */
function nearestBusStop(x,z){
  var best=null, bd=1e18;
  try{
    var MB=window.MARTA_BUS, i, s, dx, dz, d2;
    for (i=0;i<MB.stops.length;i++){
      s=MB.stops[i]; dx=x-s.x; dz=z-s.z; d2=dx*dx+dz*dz;
      if (d2<bd){ bd=d2; best=s; }
    }
  }catch(e){}
  return best;
}
/* nearestStation(x,z) — closest built MARTA rail station record, or null. */
function nearestStation(x,z){
  var best=null, bd=1e18;
  try{
    var MT=window.MARTA, i, st, dx, dz, d2;
    for (i=0;i<MT.stations.length;i++){
      st=MT.stations[i]; dx=x-st.x; dz=z-st.z; d2=dx*dx+dz*dz;
      if (d2<bd){ bd=d2; best=st; }
    }
  }catch(e){}
  return best;
}
/* assignTransit(n) — gives a commuter its NEAREST stop/station target.
   Nearest (not random) so the walk is actually reachable. Returns true
   when assigned. */
function assignTransit(n){
  try{
    if (n.commuter===1){
      var s=nearestBusStop(n.x,n.z);
      if (!s) return false;
      n.transit={kind:'bus', stop:s};
      n.goto={x:s.x, z:s.z};
      n.gotoT=TR_GOTO_T;
      return true;
    }
    if (n.commuter===2){
      var st=nearestStation(n.x,n.z);
      if (!st) return false;
      n.transit={kind:'train', stationName:st.name, station:st};
      n.goto={x:st.x, z:st.z};
      n.gotoT=TR_GOTO_T;
      return true;
    }
  }catch(e){}
  return false;
}
/* settleAtStop(n) — on arrival at a bus stop, nudge to a standing spot just
   off the sign pole (pole collider r=0.35 at the stop coords; the sign sits
   on the road shoulder per the v2.0 placement rules, so standing here is
   never in a driving lane). Tries 4 offsets; keeps the arrival spot if all
   are blocked. */
function settleAtStop(n){
  try{
    var s=n.transit&&n.transit.stop; if(!s) return;
    var offs=[[1.2,0.8],[-1.2,0.8],[1.2,-0.8],[-1.2,-0.8]], i, wx, wz;
    for (i=0;i<offs.length;i++){
      wx=s.x+offs[i][0]; wz=s.z+offs[i][1];
      if (!npcBlocked(wx,wz,n)){ n.x=wx; n.z=wz; separateNPC(n); separateFromPlayer(n); return; }
    }
  }catch(e){}
}
/* settleAtStation(n) — on arrival at a train station, step onto the platform
   deck (platY) at a small random offset so commuters don't stack on one
   spot. lockY pins the render height — renderNPCs would otherwise drop them
   back to terrain height every frame. Platform is 10u x 76u; offsets stay
   well inside it. */
function settleAtStation(n){
  try{
    var st=n.transit&&n.transit.station; if(!st) return;
    var ax=-(st.pz||0), az=(st.px||0);   // along-track unit (perp of perp)
    var al=(Math.random()*2-1)*8, pp=(Math.random()*2-1)*2;
    n.x=st.x+ax*al+(st.px||0)*pp;
    n.z=st.z+az*al+(st.pz||0)*pp;
    n.y=st.platY||n.y; n.lockY=true;
  }catch(e){}
}
/* npcRespawn(n) — the NPC "rode away": regenerate it in place (same object,
   so the 40 render slots stay valid) as a fresh spawn — new spot, new look,
   new commuter roll. It re-enters the world as if it got off somewhere
   else. Never throws. */
function npcRespawn(n){
  try{
    var fresh=spawnNPC(n.id);
    for (var k in fresh) n[k]=fresh[k];
  }catch(e){}
}
/* transitTick() — staggered (every 15 frames) from updateNPCs:
   1. Assigns transit targets to commuters whose systems just booted.
      Long-unassigned commuters (system never boots) revert to wanderers.
   2. Finds dwelling buses/trains and starts boarding for waiting NPCs
      whose stop/station matches: buses match by stop-object identity
      (same live records), trains by station name (stations are deduped
      by name across lines). */
var _trAssignT=0;
function transitTick(){
  if (!npcReady) return;
  var i, n;
  // 1. commuter assignment — cheap: only unassigned commuters are scanned
  _trAssignT++;
  if ((_trAssignT%4)===0){
    for (i=0;i<npcs.length;i++){
      n=npcs[i];
      if (n.commuter && !n.transit && !n.goto && !n.waiting && !n.boarding){
        if (transitReady(n.commuter)){ assignTransit(n); }
        else {
          n.commT=(n.commT||0)+1;
          if (n.commT>360){ n.commuter=0; }  // ~90s: system never booted, wander
        }
      }
    }
  }
  // 2. boarding: match dwelling vehicles to waiting NPCs
  var dwellers=[];
  try{
    var MB=window.MARTA_BUS;
    if (MB&&MB.ready){
      for (i=0;i<MB.buses.length;i++){
        var b=MB.buses[i];
        if (b.state==='dwell'&&b.stopIdx>=0&&b.route&&b.route.stops[b.stopIdx])
          dwellers.push({kind:'bus', ref:b, stop:b.route.stops[b.stopIdx]});
      }
    }
  }catch(e){}
  try{
    var MT=window.MARTA;
    if (MT&&MT.ready){
      for (var j=0;j<MT.trains.length;j++){
        var t=MT.trains[j];
        if (t.state==='dwell'&&t.stopIdx>=0&&t.line&&t.line.stops[t.stopIdx])
          dwellers.push({kind:'train', ref:t, name:t.line.stops[t.stopIdx].name});
      }
    }
  }catch(e){}
  if (!dwellers.length) return;
  for (i=0;i<npcs.length;i++){
    n=npcs[i];
    if (!n.waiting||n.boarding||!n.transit) continue;
    for (var d=0;d<dwellers.length;d++){
      var dw=dwellers[d], match=false;
      if (dw.kind==='bus'&&n.transit.kind==='bus'&&n.transit.stop===dw.stop) match=true;
      if (dw.kind==='train'&&n.transit.kind==='train'&&dw.name&&n.transit.stationName===dw.name) match=true;
      if (match){
        n.boarding={kind:dw.kind, ref:dw.ref};
        n.waiting=false; n.focus=false; n.boardT=TR_BOARD_T;
        n.state=ST_WALK;
        break;
      }
    }
  }
}
/* npcWaitingStops() — stops (live MARTA_BUS stop objects) with NPCs
   currently waiting. The smart-stop system queries this so buses only stop
   where passengers wait. Identity matches the bus system's stop records. */
window.npcWaitingStops=function(){
  var out=[], seen={};
  try{
    for (var i=0;i<npcs.length;i++){
      var n=npcs[i];
      if (n.waiting&&n.transit&&n.transit.kind==='bus'&&n.transit.stop){
        var s=n.transit.stop, key=s.name+'|'+s.x+'|'+s.z;
        if (!seen[key]){ seen[key]=1; out.push(s); }
      }
    }
  }catch(e){}
  return out;
};

/* ---------------- main-loop entry ---------------- */
/* updateNPCs(dt, playerPos) — frame tick (wired by the build agent into
   animate()): AI for all 1000 NPCs always runs (data-only), slots refresh
   every 0.5s, bodies render, Report publishes every 5s. When the player is
   driving, the streaming center follows the CAR, not the player on foot.
   dt clamped to 50ms. Never throws. */
function updateNPCs(dt, playerPos){
  if (!npcReady) return;
  try{
    dt=Math.min(0.05, dt||0.016);
    npcTick++;
    var px, pz;
    if (playerPos && isFinite(playerPos.x)){ px=playerPos.x; pz=playerPos.z; }
    else if (typeof player!=='undefined' && player){ px=player.x; pz=player.z; }
    else return;
    try{ cachePlayerPos(); }catch(e){}   // v1.21: NPC-vs-player collision cache (on-foot player is solid)
    try{ if (typeof car!=='undefined' && car && car.driving){ px=car.x; pz=car.z; } }catch(e){}
    var i;
    try{ npcFaceTick(dt,px,pz); }catch(e){}   // v1.14: NPCs turn to face a nearby player
    if ((npcTick%15)===0){ try{ transitTick(); }catch(e){} }  // v1.17: transit commuters (staggered)
    rebuildNpcHash();   // v1.20: NPC-NPC collision spatial hash (persistent arrays, zero garbage)
    // v1.15 DISTANCE CULLING (Joshua 2026-10-10): skip AI for NPCs beyond
    // cull distance — massive perf win on low-end phones. Culled NPCs freeze
    // in place (no AI, no movement) until player gets closer.
    var _zu = window.ZONEUNLOCK;
    for (i=0;i<npcs.length;i++){
      var _n=npcs[i];
      if(_zu && _n && _zu.shouldCull(_n.x,_n.z)) continue;
      aiNPC(_n,dt);
    }
    streamT-=dt;
    if (streamT<=0){ streamT=0.5; refreshSlots(px,pz); }
    renderNPCs(dt,px,pz);
    repT-=dt;
    if (repT<=0){ repT=5; publishReport(); }
  }catch(e){}
}
window.updateNPCs=updateNPCs;
/* debug/testing handles: window.npcTransitTick (staggered transit tick),
   window.NPC_DEBUG.npcs / .glitches for the inspector rig */
window.npcTransitTick=transitTick;
window.NPC_DEBUG={ get npcs(){return npcs;}, get glitches(){return glitchLog;} };

tryInit();
})();
