/* ============================================================================
   FILE: npc_system.js — "Surviving Adamsville" pedestrian system (~1,000 NPCs)
   ----------------------------------------------------------------------------
   PURPOSE: Free-thinking pedestrian population streaming around the player.
   KEY SYSTEMS:
     - Population: NPC_COUNT=1000 plain data objects (positions only) — no
       geometry unless near the player. Placement is DETERMINISTIC (seeded
       mulberry32, seed 19951013): stable spawns across loads. AI uses
       Math.random (non-deterministic behavior).
     - Free-think AI: no waypoints, no pathfinding — WALK a heading for a few
       seconds, IDLE (look around), TURN to a new heading; a 3.2u lookahead
       probe turns the NPC away from blockages. Simple sim, Joshua's rule.
     - Streaming renderer: only MAX_VISIBLE=40 bodies within 150u of the
       camera get instanced bodies (hysteresis: released beyond 200u), 6
       InstancedMeshes (torso/head/2 arms/2 legs), per-instance colors
       (skin head+arms = short-sleeve look, shirt torso, pants legs).
       Limb animation only within 80u (LOD); distant bodies are static.
       TCL T513V (Joshua's phone) budget drove these caps.
     - Border containment: BORDER convex quad → inward half-planes, 10u inner
       margin; NPCs turn around at the world edge instead of walking out.
     - NPC QA testers: every NPC files "glitch dispatch calls" into the
       Report when stuck >5s, blocked >10 failed turns, or in deep water —
       Joshua's live audit of broken geometry.
   JOSHUA SPECS ENCODED:
     - NPC population ~1,000: adult men (~45%), adult women (~40%), and a
       smaller number of 16-year-old boys (~15%). NOBODY under 16, NOBODY
       over 65 — hard rule, encoded in TYPE_NAMES and the age-16 boy model
       (0.85 scale). No children, no elderly.
     - Pedestrians never spawn on highways (I-20/85/75/285).
     - Spawn mix: 55% roadside (off the asphalt: half-width + 2.5-5.5u),
       20% commercial, 25% residential.
     - LIFE SIM (queued, not yet in this file): each NPC can have a home
       residence, a car, and a workplace — unassigned shows "unspecified";
       Joshua assigns homes from a dropdown of houses/apartments. Building
       entry is fade/morph-through-the-door (no door animation) — NPC
       disappears inside a while, reappears when leaving.
   ============================================================================ */
/* ============================================================================
   NPC PEDESTRIAN SYSTEM — "Surviving Adamsville" v1.9
   ~1,000 free-think pedestrians. Each NPC is DATA ONLY when distant
   (no geometry, no Three.js objects). Bodies stream in as instanced boxes
   only near the camera. Every NPC is also a QA tester: when one hits a
   problem it files a glitch dispatch call into the Report.

   ---- INTEGRATION (build agent: 2 steps, do NOT edit this file) ----
   1. In index.html, AFTER the main inline <script>...</script> block
      (right before </body>), add:
          <script src="npc_system.js"></script>
      (Must load after the main script: it needs roadDrawData, PLACED_HOUSES,
      bldgGrid, BORDER, heightAt(), onRoad(), inWater(), waterDepthAt(),
      Report, THREE and scene to exist.)
   2. In animate(), after updateCamera(dt); add:
          try{ updateNPCs(dt, player.mesh.position); }catch(e){}

   Reads (all optional/guarded — the system degrades gracefully if one is
   missing): player, car, roadDrawData, PLACED_HOUSES, OSM_BUILDINGS,
   bldgGrid, BORDER, heightAt, onRoad, inWater, waterDepthAt, Report.
   Writes: 6 InstancedMeshes added to scene; window.updateNPCs;
   Report.setSys('npc', ...) every 5s.
   ============================================================================ */
(function npcPedestrians(){
'use strict';

/* ---------------- config ---------------- */
var NPC_COUNT   = 1000;   // Joshua's spec: ~1,000 pedestrians
var MAX_VISIBLE = 40;     // hard cap on instanced bodies (TCL T513V budget)
var VISIBLE_R   = 150;    // stream a body in within this distance (u)
var HIDE_R      = 200;    // release the body beyond this distance (hysteresis)
var ANIM_R      = 80;     // limb animation only inside this range (LOD)
var ST_WALK = 0, ST_IDLE = 1, ST_TURN = 2;
var STATE_NAMES = ['WALK','IDLE','TURN'];
var TYPE_NAMES  = ['man','woman','boy16'];   // nobody under 16, nobody over 65

/* 1995-Atlanta palettes. Skin: range of brown tones (per spec). */
var SKINS  = [0x4a2f1c,0x5a3a24,0x6b4429,0x7d5230,0x8a5f36,0x93683c,0xa07a48];
var SHIRTS = [0xc23b2e,0x2e5fa3,0x2e8b57,0xe0e0e0,0xe8b923,0x1f8a8a,0xd96c2c,
              0x7b4fa3,0x555c66,0x222226,0xb03060,0x3a7d44,0xc7c7c7,0x8a2be2];
var PANTS  = [0x2e4a6b,0x1f2a3a,0x141414,0x9a8a6a,0x5a4632,0x666c75,0x3b3f4a];

/* ---------------- state ---------------- */
var npcs=[];            // the population: plain data objects, nothing else
var slots=[];           // MAX_VISIBLE entries: npc ref or null
var glitchLog=[];       // newest 50 dispatch calls
var glitchTotal=0;
var npcReady=false, npcTick=0, visCount=0;
var streamT=0, repT=0;

/* scratch / temps — allocated once, never in the hot loop */
var _m1=null,_m2=null,_m3=null,_m4=null,_m5=null,_m6=null,_m7=null,_out=null;
var _col=null, _free=[], _mesh=null;   // _mesh: {torso,head,armL,armR,legL,legR}
var walkRoads=[], comSpots=[], resSpots=[];
var borderOK=null;      // null = no constraint; else {px,py...} half-planes

/* Deterministic RNG for PLACEMENT ONLY (stable spawns). AI uses Math.random. */
function mulberry32(a){
  return function(){
    a|=0; a=a+0x6D2B79F5|0;
    var t=Math.imul(a^a>>>15,1|a);
    t=t+Math.imul(t^t>>>7,61|t)^t;
    return ((t^t>>>14)>>>0)/4294967296;
  };
}
var srand=mulberry32(19951013);

/* ---------------- border containment ----------------
   BORDER is a convex quad [{x,z}x4]. Precompute inward half-planes so NPCs
   TURN around instead of wandering out of the world. 10u inner margin. */
/* buildBorder() — precomputes the BORDER polygon's inward-facing half-planes
   (one per edge) so insideBorder() can cheaply test containment. BORDER is a
   convex quad; edge direction follows the polygon's winding (s=+1/-1). */
function buildBorder(){
  try{
    if (typeof BORDER==='undefined'||!BORDER||BORDER.length<3){ borderOK=null; return; }
    var n=BORDER.length, i, area=0;
    for (i=0;i<n;i++){ var a=BORDER[i], b=BORDER[(i+1)%n]; area+=a.x*b.z-b.x*a.z; }
    var s=area>0?1:-1, E=[];
    for (i=0;i<n;i++){
      var p=BORDER[i], q=BORDER[(i+1)%n];
      var ex=q.x-p.x, ez=q.z-p.z, L=Math.hypot(ex,ez)||1;
      E.push({px:p.x,pz:p.z,ex:ex/L,ez:ez/L,s:s});
    }
    borderOK=E;
  }catch(e){ borderOK=null; }
}
/* insideBorder(x,z) — true when (x,z) is at least 10u inside every border
   edge. The 10u margin keeps NPCs off the world wall. Returns true when no
   border constraint exists. */
function insideBorder(x,z){
  if (!borderOK) return true;
  for (var i=0;i<borderOK.length;i++){
    var e=borderOK[i];
    var cr=e.ex*(z-e.pz)-e.ez*(x-e.px);   // cross(edge, point-p)
    if (e.s*cr < 10) return false;        // 10u margin inside the wall
  }
  return true;
}

/* ---------------- blockage probe ----------------
   Cheap "can I step here?" test: water, road corridor, OSM building
   colliders (spatial grid, cell 40u — same grid the game uses), ranch
   houses (PLACED_HOUSES is small, direct loop). Trees/furniture are
   intentionally ignored: walking past a trunk is invisible at this scale. */
/* npcBlocked(x,z) — cheap "can I step here?" probe. Returns true for water,
   road corridors, border edges, OSM building colliders (40u spatial grid —
   the same grid the game uses), and ranch houses (small list, direct loop).
   Trees/furniture are INTENTIONALLY ignored: walking past a trunk is
   invisible at this scale, and checking them would cost far more than it
   saves. All wrapped — a missing world feature degrades to "not blocked". */
function npcBlocked(x,z){
  try{
    if (typeof inWater==='function' && inWater(x,z)) return true;
    if (typeof onRoad==='function' && onRoad(x,z)) return true;
    if (!insideBorder(x,z)) return true;
    if (typeof bldgGrid!=='undefined' && bldgGrid){
      var cx=Math.floor(x/40), cz=Math.floor(z/40);
      for (var gx=cx-1;gx<=cx+1;gx++) for (var gz=cz-1;gz<=cz+1;gz++){
        var cell=bldgGrid[gx+','+gz]; if(!cell) continue;
        for (var i=0;i<cell.length;i++){
          var c=cell[i], dx=x-c.x, dz=z-c.z, rr=c.r+0.7;
          if (dx*dx+dz*dz < rr*rr) return true;
        }
      }
    }
    if (typeof PLACED_HOUSES!=='undefined' && PLACED_HOUSES){
      for (var j=0;j<PLACED_HOUSES.length;j++){
        var h=PLACED_HOUSES[j];
        var hx=x-h[0], hz=z-h[1], hr=Math.max(h[2],h[3])/2+1.7;
        if (hx*hx+hz*hz < hr*hr) return true;
      }
    }
  }catch(e){}
  return false;
}

/* ---------------- glitch dispatch ----------------
   Every NPC is a QA tester. problem = what went wrong; what = what it was
   doing (state); why = its intent. Newest 50 kept. */
/* npcGlitch(n, problem, what, why) — files one NPC QA dispatch call: who
   (NPC#id + type), where (rounded x,z), what they were doing (state), why
   (intent), and what went wrong. Keeps the newest 50; forces the next report
   tick (repT=0) so the Report panel shows it promptly. Joshua reads these
   as his live geometry audit. */
function npcGlitch(n, problem, what, why){
  glitchTotal++;
  try{
    glitchLog.push({
      caller: 'NPC#'+n.id+' ('+TYPE_NAMES[n.type]+')',
      location: [+n.x.toFixed(1), +n.z.toFixed(1)],
      what: what || STATE_NAMES[n.state],
      why: why || 'deciding where to go',
      problem: problem,
      t: new Date().toISOString()
    });
    if (glitchLog.length>50) glitchLog.splice(0, glitchLog.length-50);
    repT=0;   // publish on the next frame
  }catch(e){}
}

/* ---------------- spawn placement (deterministic) ---------------- */
/* collectSpots() — builds the three spawn pools once: walkRoads (non-highway
   roads only — nobody spawns on I-20/85/75/285), comSpots (OSM type 1/2 =
   commercial/apartment), resSpots (PLACED_HOUSES). Called once at init. */
function collectSpots(){
  walkRoads=[]; comSpots=[]; resSpots=[];
  try{
    if (typeof roadDrawData!=='undefined' && roadDrawData)
      for (var i=0;i<roadDrawData.length;i++){
        var r=roadDrawData[i];
        // no pedestrians spawning on highways (I-20/85/75/285)
        if (r && r.pts && r.pts.length>=2 && r.cat!=='highway') walkRoads.push(r);
      }
  }catch(e){}
  try{
    // OSM types: 0 house, 1 commercial, 2 apartment/large, 3 other
    if (typeof OSM_BUILDINGS!=='undefined' && OSM_BUILDINGS)
      for (var j=0;j<OSM_BUILDINGS.length;j++){
        var b=OSM_BUILDINGS[j];
        if (b && (b[5]===1||b[5]===2)) comSpots.push(b);
      }
  }catch(e){}
  try{
    if (typeof PLACED_HOUSES!=='undefined' && PLACED_HOUSES)
      for (var k=0;k<PLACED_HOUSES.length;k++) resSpots.push(PLACED_HOUSES[k]);
  }catch(e){}
}
/* roadsideSpot() — random point along a random non-highway road, offset
   perpendicular (half-width + 2.5-5.5u, random side) so the spawn is OFF the
   asphalt — pedestrians start on the shoulder/grass, never in traffic. */
function roadsideSpot(){
  var r=walkRoads[(srand()*walkRoads.length)|0];
  var pts=r.pts, si=(srand()*(pts.length-1))|0;
  var a=pts[si], b=pts[si+1], t=srand();
  var x=a[0]+(b[0]-a[0])*t, z=a[1]+(b[1]-a[1])*t;
  var dx=b[0]-a[0], dz=b[1]-a[1], L=Math.hypot(dx,dz)||1;
  var side=srand()<0.5?1:-1, off=r.w/2+2.5+srand()*3;   // off the asphalt
  return [x+(-dz/L)*off*side, z+(dx/L)*off*side];
}
/* nearSpot(list, isOSM) — random point on a ring around a building
   (half the building's footprint + 3-9u out): "near the building" without
   being inside it. isOSM picks the OSM [x,z,w,d,...] layout vs the
   PLACED_HOUSES [x,z,w,d] layout. */
function nearSpot(list, isOSM){
  var s=list[(srand()*list.length)|0];
  var w=isOSM?s[2]:s[2], d=isOSM?s[3]:s[3];
  var ang=srand()*Math.PI*2, dist=Math.max(w,d)/2+3+srand()*6;
  return [s[0]+Math.cos(ang)*dist, s[1]+Math.sin(ang)*dist];
}
/* spawnNPC(id) — creates one NPC data object: up to 12 placement tries
   (55% roadside / 20% commercial / 25% residential, falling back to roadside
   when a pool is empty; [4000,6000] is the last-resort map middle), then
   type by roll (45% man / 40% woman / 15% boy16 — Joshua's age rule: nobody
   under 16, nobody over 65), walk speed by type (boys fastest: 1.6-2.1 u/s),
   0.85 body scale for boys, 3 random body-width variants, and randomized
   skin (brown tones per spec)/shirt/pants. Speeds use srand (stable) at
   spawn; AI uses Math.random per frame. */
function spawnNPC(id){
  var pt=null, tries=0, roll=srand();
  // 55% roadside / 20% commercial / 25% residential (fall back to roadside)
  while (tries<12){
    if (roll<0.55 || (roll<0.75 && !comSpots.length) || (roll>=0.75 && !resSpots.length)){
      if (walkRoads.length) pt=roadsideSpot();
    } else if (roll<0.75){
      pt=nearSpot(comSpots,true);
    } else {
      pt=nearSpot(resSpots,false);
    }
    if (!pt){ pt=[4000,6000]; break; }                 // last-resort map middle
    if (!npcBlocked(pt[0],pt[1])) break;              // good spot
    tries++;
  }
  var tr=srand();
  var type= tr<0.45?0 : (tr<0.85?1:2);                 // 45% men / 40% women / 15% boys
  var n={
    id:id, x:pt[0], z:pt[1], heading:srand()*Math.PI*2,
    state: srand()<0.7?ST_WALK:ST_IDLE,
    stateT: 1+srand()*4, speed: 0, seed: srand(), type: type,
    y:0, phase:srand()*6.28, walkAmt:0, slot:-1,
    lx:pt[0], lz:pt[1], stuckT:0, fails:0, _pick:false,
    scl:  type===2?0.85:1.0,                          // 16yo boys: 0.85 scale
    wid:  type===2?0.9:[0.9,1.0,1.18][(srand()*3)|0],  // 3 body-type widths
    skin: SKINS[(srand()*SKINS.length)|0],
    shirt:SHIRTS[(srand()*SHIRTS.length)|0],
    pants:PANTS[(srand()*PANTS.length)|0]
  };
  n.speed = type===0 ? 1.3+srand()*0.4 : type===1 ? 1.2+srand()*0.4 : 1.6+srand()*0.5;
  try{ n.y=(typeof clampVehY==='function')?clampVehY(n.x,n.z,heightAt(n.x,n.z)):heightAt(n.x,n.z); }catch(e){ n.y=0; }
  n.lx=n.x; n.lz=n.z;
  return n;
}

/* ---------------- free-think AI ----------------
   No waypoints, no pathfinding. WALK a heading for a few seconds, IDLE and
   look around, TURN to a new heading. Sample ahead; if blocked, TURN.
   PERF trick: the lookahead probe and stuck check are staggered per NPC
   ((npcTick+n.id)%18 and %60) so only ~1/18th of the population probes per
   frame — 1000 NPCs × probes every frame would be too slow on the TCL. */
/* aiNPC(n, dt) — one AI tick:
     WALK: advance along heading; every ~0.3s probe 3.2u ahead and TURN if
       blocked; every ~1s check displacement (moved <0.6u while walking =
       stuck): after 5s file a glitch and TURN; unexpected deep water also
       files a glitch. Timer end → 35% IDLE, else TURN.
     IDLE: gentle sinusoidal heading wander (look around), no position drift.
     TURN: pick a random new heading, probe it; walk it if clear, else retry —
       after 10 failed turns file a glitch and walk anyway (the stuck
       detector watches; better to keep moving than spin forever). */
/* setState(n, st, t) — sets the NPC's AI state and its countdown timer. */
function setState(n, st, t){ n.state=st; n.stateT=t; }
function aiNPC(n, dt){
  /* v1.14: conversation focus — the NPC is facing the player for a chat.
     Pause the wander AI (no walking off, no state-timer expiry) while
     npcFaceTick eases the heading toward the player. */
  if (n.focus){ n.stateT=Math.max(n.stateT,0.5); return; }
  n.stateT-=dt;
  if (n.state===ST_WALK){
    var step=n.speed*dt;
    n.x+=Math.sin(n.heading)*step;
    n.z+=Math.cos(n.heading)*step;
    // staggered lookahead probe (~every 0.3s per NPC at 60fps)
    if ( ((npcTick+n.id)%18)===0 ){
      var px=n.x+Math.sin(n.heading)*3.2, pz=n.z+Math.cos(n.heading)*3.2;
      if (npcBlocked(px,pz)){ n.fails++; setState(n,ST_TURN,0); }
    }
    // staggered stuck check (~every 1s): moved <0.6u while walking = stuck
    if ( ((npcTick+n.id)%60)===0 ){
      var dx=n.x-n.lx, dz=n.z-n.lz;
      if (dx*dx+dz*dz < 0.36){ n.stuckT++; } else { n.stuckT=0; }
      n.lx=n.x; n.lz=n.z;
      if (n.stuckT>=5){
        npcGlitch(n,'stuck on geometry for >5s','WALK','heading somewhere');
        n.stuckT=0; n.fails=0; setState(n,ST_TURN,0);
      }
      // deep water should never happen (probes avoid it) — report if it does
      try{
        if (typeof waterDepthAt==='function' && waterDepthAt(n.x,n.z)>1.2){
          npcGlitch(n,'entered deep water unexpectedly','WALK','heading somewhere');
          setState(n,ST_TURN,0);
        }
      }catch(e){}
    }
    if (n.stateT<=0){
      if (Math.random()<0.35) setState(n,ST_IDLE,1+Math.random()*2);  // pause, look around
      else setState(n,ST_TURN,0);
    }
  }
  else if (n.state===ST_IDLE){
    // "look around": gentle sinusoidal heading wander, no drift
    n.heading+=Math.sin(npcTick*0.05+n.seed*6.283)*0.4*dt;
    if (n.stateT<=0) setState(n,ST_TURN,0);
  }
  else { // ST_TURN: pick a heading, verify it, walk it — or try another
    n.heading+=(Math.random()*2-1)*2.4;
    var tx=n.x+Math.sin(n.heading)*3.2, tz=n.z+Math.cos(n.heading)*3.2;
    if (!npcBlocked(tx,tz)){
      n.fails=0; setState(n,ST_WALK,2.5+Math.random()*3.5);
    } else {
      n.fails++;
      if (n.fails>10){
        npcGlitch(n,'blocked repeatedly ('+n.fails+' failed turns)','TURN',
                  'trying to find a walkable heading');
        n.fails=0; setState(n,ST_WALK,2);   // walk anyway; stuck-detector watches
      }
    }
  }
}

/* ---------------- streaming: bodies only near the camera ---------------- */
/* assignSlot(s,n) — binds NPC n to render slot s and bakes its per-instance
   colors: skin on head+arms (short-sleeve look), shirt on torso, pants on
   legs. Slot count is set to the visible count each frame; unassigned slots
   are never drawn. */
function assignSlot(s,n){
  n.slot=s; slots[s]=n;
  _col.set(n.skin);
  _mesh.head.setColorAt(s,_col); _mesh.armL.setColorAt(s,_col); _mesh.armR.setColorAt(s,_col);
  _col.set(n.shirt); _mesh.torso.setColorAt(s,_col);
  _col.set(n.pants); _mesh.legL.setColorAt(s,_col); _mesh.legR.setColorAt(s,_col);
  var mk=[_mesh.torso,_mesh.head,_mesh.armL,_mesh.armR,_mesh.legL,_mesh.legR];
  for (var i=0;i<mk.length;i++) if (mk[i].instanceColor) mk[i].instanceColor.needsUpdate=true;
}
/* refreshSlots(px,pz) — reassigns the 40 render slots every 0.5s: releases
   NPCs beyond HIDE_R (200u — hysteresis so bodies don't pop at the
   VISIBLE_R 150u boundary), then fills freed slots with the nearest
   unslotted NPCs inside VISIBLE_R. No allocation: a _pick flag on each NPC
   prevents double-picking within one pass, and _free is a reused scratch
   array. Note: the fill scan is O(slots × npcs) — acceptable at 0.5s
   cadence, would not be per frame. */
function refreshSlots(px,pz){
  var VR2=VISIBLE_R*VISIBLE_R, HR2=HIDE_R*HIDE_R, i, s, n;
  _free.length=0;
  for (s=0;s<MAX_VISIBLE;s++){
    n=slots[s];
    if (n){
      var dx=n.x-px, dz=n.z-pz;
      if (dx*dx+dz*dz>HR2){ n.slot=-1; slots[s]=null; _free.push(s); }
    } else _free.push(s);
  }
  // fill freed slots with the nearest unslotted NPCs (no allocation: flag scan)
  for (var f=0;f<_free.length;f++){
    var best=null, bestD=VR2;
    for (i=0;i<npcs.length;i++){
      n=npcs[i];
      if (n.slot>=0||n._pick) continue;
      var ex=n.x-px, ez=n.z-pz, d2=ex*ex+ez*ez;
      if (d2<bestD){ bestD=d2; best=n; }
    }
    if (!best) break;
    best._pick=true; assignSlot(_free[f],best);
  }
  for (i=0;i<npcs.length;i++) npcs[i]._pick=false;
}

/* ---------------- rendering: 6 InstancedMeshes, ~6-10 boxes per NPC ----------------
   One unit box per part, scaled by matrix. Per-instance colors: skin on head
   + arms (short-sleeve look), shirt on torso, pants on legs. Boys render at
   0.85 scale; 3 width variants via wid. */
/* partMat(...) — composes one body-part's matrix from 7 premultiplied
   matrices: world translate → yaw → body scale → part offset → limb swing
   (rotation X) → pivot drop → part size. All scratch matrices are allocated
   once at init (never in the hot loop); _out is returned. */
function partMat(wx,wy,wz,yaw,scl, px,py,pz, swing,drop, sx,sy,sz){
  _m1.makeTranslation(wx,wy,wz);
  _m2.makeRotationY(yaw);
  _m3.makeScale(scl,scl,scl);
  _m4.makeTranslation(px,py,pz);
  _m5.makeRotationX(swing);
  _m6.makeTranslation(0,drop,0);
  _m7.makeScale(sx,sy,sz);
  return _out.copy(_m1).multiply(_m2).multiply(_m3)
              .multiply(_m4).multiply(_m5).multiply(_m6).multiply(_m7);
}
/* renderNPCs(dt,px,pz) — writes body-part matrices for every slotted NPC.
   walkAmt eases toward 1 (walking) / 0 (idle) so limbs don't snap; the walk
   phase advances at 3.2+speed*2.6 rad/s; legs swing opposed (sw / -sw),
   arms counter-swing (asw / -asw); distant NPCs get a static pose
   (ANIM_R=80u LOD — animation only near the camera). A non-finite terrain
   height is reported as a "fell through world" glitch and clamped to the
   last good height. */
function renderNPCs(dt,px,pz){
  var s, n, vis=0, AR2=ANIM_R*ANIM_R;
  for (s=0;s<MAX_VISIBLE;s++){
    n=slots[s]; if(!n) continue;
    vis++;
    var dx=n.x-px, dz=n.z-pz, near=(dx*dx+dz*dz)<AR2;
    var y; try{ y=heightAt(n.x,n.z); }catch(e){ y=NaN; }
    if (!isFinite(y)){
      npcGlitch(n,'fell through world','WALK','standing on terrain');
      y=isFinite(n.y)?n.y:0;
    }
    if (typeof clampVehY==='function') y=clampVehY(n.x,n.z,y);  // v1.12: ground clamp — no sky-floaters
    n.y=y;
    var target=(n.state===ST_WALK)?1:0;
    n.walkAmt+=(target-n.walkAmt)*Math.min(1,6*dt);
    if (near && n.walkAmt>0.02) n.phase+=dt*(3.2+n.speed*2.6)*n.walkAmt;
    var sw=Math.sin(n.phase)*0.55*n.walkAmt;       // legs oppose...
    var asw=Math.sin(n.phase)*0.45*n.walkAmt;      // ...arms counter-swing
    if (!near){ sw=0; asw=0; }                    // distant: static pose
    var scl=n.scl, yaw=n.heading, wid=n.wid;
    _mesh.torso.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, 0,1.075,0, 0,0, 0.42*wid,0.55,0.26*wid));
    _mesh.head.setMatrixAt (s, partMat(n.x,y,n.z,yaw,scl, 0,1.49,0,  0,0, 0.24,0.28,0.24));
    _mesh.armL.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, -0.265*wid,1.28,0, -asw,-0.29, 0.11,0.58,0.11));
    _mesh.armR.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl,  0.265*wid,1.28,0,  asw,-0.29, 0.11,0.58,0.11));
    _mesh.legL.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl, -0.115*wid,0.80,0,  sw,-0.33, 0.15,0.66,0.15));
    _mesh.legR.setMatrixAt(s, partMat(n.x,y,n.z,yaw,scl,  0.115*wid,0.80,0, -sw,-0.33, 0.15,0.66,0.15));
  }
  visCount=vis;
  var mk=[_mesh.torso,_mesh.head,_mesh.armL,_mesh.armR,_mesh.legL,_mesh.legR];
  for (var i=0;i<mk.length;i++){ mk[i].count=vis; mk[i].instanceMatrix.needsUpdate=true; }
}

/* publishReport() — pushes the NPC status to the Report panel every 5s:
   population, visible count, and the live glitch log (Joshua's NPC QA
   dispatch calls). Guarded — safe when Report isn't loaded. */
function publishReport(){
  try{
    if (typeof Report!=='undefined' && Report.setSys){
      Report.setSys('npc',{
        count:npcs.length, visible:visCount, maxVisible:MAX_VISIBLE,
        glitchReports:glitchLog.slice(), glitchTotal:glitchTotal,
        note:'free-think pedestrians (WALK/IDLE/TURN, no waypoints); bodies stream in under 150u'
      });
    }
  }catch(e){}
}

/* ---------------- init ---------------- */
/* initNPCs() — allocates scratch matrices, builds the border, fills spawn
   pools, creates all 1000 NPCs, the 40 render slots, and the 6
   InstancedMeshes (one per body part, unit-box geometry scaled per part).
   Meshes are frustumCulled=false (positions update every frame; culling the
   batch would hide everyone) with cast/receive shadows off for perf. */
function initNPCs(){
  _m1=new THREE.Matrix4(); _m2=new THREE.Matrix4(); _m3=new THREE.Matrix4();
  _m4=new THREE.Matrix4(); _m5=new THREE.Matrix4(); _m6=new THREE.Matrix4();
  _m7=new THREE.Matrix4(); _out=new THREE.Matrix4();
  _col=new THREE.Color();
  buildBorder();
  collectSpots();
  for (var i=0;i<NPC_COUNT;i++) npcs.push(spawnNPC(i));
  for (var s=0;s<MAX_VISIBLE;s++) slots.push(null);
  var unitBox=new THREE.BoxGeometry(1,1,1);
  function im(){
    var m=new THREE.InstancedMesh(unitBox,
      new THREE.MeshLambertMaterial({color:0xffffff}), MAX_VISIBLE);
    m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
    m.frustumCulled=false;      // positions update every frame; never cull the batch
    m.castShadow=false; m.receiveShadow=false;
    m.count=0; scene.add(m); return m;
  }
  _mesh={ torso:im(), head:im(), armL:im(), armR:im(), legL:im(), legR:im() };
  npcReady=true;
  publishReport();
}

/* tryInit() — waits for the main script's world (THREE, scene,
   roadDrawData) to exist, then inits once. ~20s grace (40 × 500ms); after
   that the NPC system stays off and the game is unaffected. */
var initTries=0;
function tryInit(){
  try{
    if (typeof THREE==='undefined' || typeof scene==='undefined' ||
        typeof roadDrawData==='undefined' || !roadDrawData || !roadDrawData.length){
      if (++initTries<40) setTimeout(tryInit,500);   // ~20s grace
      return;
    }
    initNPCs();
  }catch(e){ /* NPC system stays off; game unaffected */ }
}

/* ---------------- NPC conversations (v1.14) ----------------
   JOSHUA'S DIRECTIVE (2026-10-09): NPCs that are NOT part of the work crew
   should talk about Atlanta. When the player walks up to one:
     1. the NPC turns to face the player,
     2. a TALK prompt appears on the universal action button
        (same pattern as ENTER CAR),
     3. tapping it opens a dialogue panel with a randomized Atlanta-themed
        line — Zoo, Aquarium, Botanical Garden, Centennial Olympic Park,
        High Museum, Fox Theatre, Ponce City Market, BeltLine, Underground
        Atlanta, Stone Mountain, World of Coca-Cola, MARTA, restaurants,
        parks, neighborhoods, events.
   NOTE: every NPC in THIS file is a pedestrian — the road crew lives in
   roadcrew_system.js, so no crew-filtering is needed here.
   While an NPC has "focus" (player nearby) it pauses its wander AI and
   eases its heading toward the player. The dialogue panel is owned by
   index.html (showNpcDialog/hideNpcDialog); this module only supplies the
   lines and the proximity/talk state. */
/* TALK_LINES — the Atlanta conversation pool. First-person, casual, PG.
   ~64 unique lines across the categories Joshua named. */
/* ============================================================================
   NPC DIALOGUE DATABASE (v1.14.1) — NPC Dialogue Director's domain.
   ----------------------------------------------------------------------------
   Joshua's directive (2026-10-09): NPCs that are NOT part of the work crew
   talk about Atlanta — attractions, food, transit, neighborhoods, events.
   When the player walks up, the NPC turns to face them and a TALK prompt
   appears on the universal action button (same pattern as ENTER CAR).

   STRUCTURE: personality pools. Every NPC type (man / woman / boy16) gets
   its own voice plus a shared pool of general Atlanta lines. npcTalkLine(n)
   merges the NPC's pool with the shared pool and picks a random line —
   never the same line twice in a row (talkLastKey tracks pool+index).

   VOICE RULES (set by the Dialogue Director):
     - All lines first-person, casual, PG. Things a real Atlanta local
       would actually say out loud to a stranger on the sidewalk.
     - boy16 lines are age-appropriate: school, friends, games, sports —
       never bars, clubs, or adult nightlife.
     - No named real people. Places are fine (they're public landmarks).
   GROWTH: add new lines to the right pool; the picker needs no changes.
   ============================================================================ */
/* TALK_SHARED — general Atlanta lines any NPC can say. */
var TALK_SHARED=[
 /* --- Zoo Atlanta --- */
 "Have you checked out Zoo Atlanta yet? The pandas are something else.",
 "I just came from the zoo — the gorillas were putting on a show today.",
 "Zoo Atlanta's got that African savanna exhibit now, you gotta see it.",
 "Took my cousins to the zoo last weekend — they loved the giraffes.",
 "The reptile house at the zoo gives me the creeps, but it's cool.",
 /* --- Georgia Aquarium --- */
 "Have you been to the Georgia Aquarium yet? It's massive!",
 "The whale sharks at the aquarium — you won't believe how big they are.",
 "I just came from the aquarium downtown. That ocean tunnel is unreal.",
 "The dolphin show at the Georgia Aquarium is worth every penny.",
 "One of the biggest aquariums in the world and it's right here. Wild.",
 /* --- Atlanta Botanical Garden --- */
 "You been to the Atlanta Botanical Garden? Beautiful this time of year.",
 "The Garden's holiday lights are the best night out in the city.",
 "I was just over at the Botanical Garden. The orchid house smells amazing.",
 "The canopy walk at the Garden — you're walking through the treetops.",
 /* --- Centennial Olympic Park --- */
 "Centennial Olympic Park is where it's at on weekends.",
 "They still run the Fountain of Rings show at the park — kids love it.",
 "I just came from Centennial Park. Perfect day for it.",
 "The park was built for the '96 Olympics. Still the heart of downtown.",
 /* --- High Museum --- */
 "The High Museum has a new exhibit — thinking about going Saturday.",
 "Have you been to the High? That building alone is a work of art.",
 "The High's folk art collection is underrated. Go see it.",
 /* --- Fox Theatre --- */
 "Have you been to the Fox Theatre? Caught a show there last week.",
 "The Fox is the prettiest building in Atlanta. Fight me.",
 "They're doing a classic movie night at the Fox next month.",
 "That Moorish architecture on the Fox — nothing else like it.",
 /* --- Ponce City Market --- */
 "Have you tried the food at Ponce City Market? So many options.",
 "I was just up at Ponce City Market — the rooftop view is crazy.",
 "Skip the line, hit the food hall at Ponce early.",
 "Ponce used to be a Sears warehouse. Now look at it.",
 /* --- Atlanta BeltLine --- */
 "The BeltLine is perfect for walking — have you been?",
 "I just biked the whole Eastside Trail. Best free thing in Atlanta.",
 "BeltLine on a Sunday afternoon — that's the move.",
 "The art on the BeltLine changes all the time. Always something new.",
 /* --- Underground Atlanta --- */
 "I was just down at Underground Atlanta. Lots of history down there.",
 "Underground's been changing a lot lately — worth another look.",
 /* --- Stone Mountain --- */
 "Stone Mountain is worth the drive, especially for the laser show.",
 "Hiked up Stone Mountain this morning — the skyline view is unreal.",
 "The train around Stone Mountain is a whole vibe.",
 /* --- World of Coca-Cola --- */
 "The World of Coca-Cola is a must-see if you haven't been.",
 "You can taste like a hundred sodas from around the world at Coca-Cola. Wild.",
 "Coke was invented right here in Atlanta. That's our thing.",
 /* --- MARTA --- */
 "Have you ridden MARTA to the airport? So convenient.",
 "The train to the airport beats sitting in Connector traffic any day.",
 "MARTA's got its problems, but the Gold Line gets me downtown fast.",
 "Pro tip: the airport station is right inside the terminal. Can't miss it.",
 /* --- Getting around --- */
 "Avoid the Downtown Connector at rush hour. Trust me on this.",
 "285 is a parking lot after 4. Plan accordingly.",
 "It rained for ten minutes and everybody forgot how to drive.",
 "Atlanta weather — wait five minutes, it'll change.",
 "The Perimeter is where the real traffic lives.",
 /* --- General Atlanta --- */
 "You new around here? Welcome to the A.",
 "This heat? Yeah, it's always like this. You'll get used to it.",
 "Have you seen the skyline at night from the Westside? Beautiful.",
 "Mercedes-Benz Stadium looks like a spaceship landed downtown.",
 "Have you been out to the Chattahoochee? Good fishing out there.",
 "Atlanta's a city in a forest. Look up — trees everywhere.",
 "The King Center downtown — everybody should visit at least once.",
 "Oakland Cemetery does tours — spooky and historic.",
 "The Center for Civil Rights downtown — powerful stuff."
];
/* TALK_MAN — adult men's pool: sports, work commute, local history. */
var TALK_MAN=[
 "Did you catch the Braves game? This city's buzzing.",
 "Falcons better get it together this season, I'm saying.",
 "Hawks are fun to watch this year. State Farm Arena gets loud.",
 "Atlanta United matches — the atmosphere is unreal. Best fans in MLS.",
 "I remember when the Braves were at Turner Field. Times change.",
 "Dragon Con takes over downtown every year — it's wild.",
 "Have you toured the CNN Center? Right by the park.",
 "Sweet Auburn — that's where Atlanta's Black history lives. Go walk it.",
 "The Varsity — been going since I was a kid. Chili dogs never miss.",
 "Best lemon pepper wings in the city? Don't even get me started.",
 "I drive the Connector every morning. Pray for me.",
 "You ever been stuck on 75/85 when it shuts down? Nightmare.",
 "They finally fixed that pothole on Cascade. Only took a year.",
 "My commute's twenty minutes unless 285 says otherwise.",
 "Adamsville's home. Been here my whole life.",
 "East Point's got that old-school Atlanta feel.",
 "Buckhead's fancy, but the real Atlanta's down here.",
 "I grew up going to Adams Park. Still play ball there sometimes.",
 "Wilson Mill Park — good spot to clear your head.",
 "You know they filmed half of Hollywood out here now? Tyler Perry Studios and all.",
 "The old GM plant in Doraville — my uncle worked there thirty years.",
 "Fulton Industrial at night — nothing but trucks and streetlights.",
 "Have you had real soul food on Cascade? Life-changing.",
 "Go to The Beautiful for breakfast. Trust me on this one.",
 "Sweet tea here hits different. It's basically the city drink."
];
/* TALK_WOMAN — adult women's pool: community, food, parks, culture. */
var TALK_WOMAN=[
 "Piedmont Park on a Saturday — everybody's out there.",
 "Grant Park is underrated. The historic homes around it are gorgeous.",
 "Have you walked the trails at Cascade Springs? Real peaceful.",
 "The farmers market in East Point on Saturdays — fresh everything.",
 "Have you been to the High Museum's Friday jazz nights? So nice.",
 "Little Five Points is... an experience. Go see for yourself.",
 "Have you been down to Castleberry Hill? The art scene is blowing up.",
 "The Fox Theatre's Mighty Mo organ — they still play it before shows.",
 "I take my niece to the Children's Museum downtown. She loves it.",
 "The Center for Puppetry Arts — sounds silly, it's actually wonderful.",
 "Have you tried the food trucks at the park? The lines move fast.",
 "Real talk — the best peach cobbler is at my church's bake sale.",
 "You gotta try the Varsity — it's an Atlanta institution.",
 "Mary Mac's Tea Room — classic Atlanta comfort food.",
 "The BeltLine's Eastside Trail is my morning walk. Every morning.",
 "Chastain Park concerts in the summer — bring a picnic.",
 "Have you seen the Swan House? It's like a movie set.",
 "The MLK historic district — take the whole tour, not just the house.",
 "I just came from Trader Joe's on Piedmont. That parking lot is a war zone.",
 "Lenox on a Saturday — I don't know why I do this to myself.",
 "The aquarium's sleepovers for kids — mine still talks about it.",
 "Zoo Atlanta's behind-the-scenes tour — worth saving up for.",
 "Have you been to the Alliance Theatre? Great shows.",
 "The Wren's Nest in West End — storytelling at its finest."
];
/* TALK_BOY16 — 16-year-old boys: school, friends, sports, games. PG, age-fit. */
var TALK_BOY16=[
 "You go to school around here? I'm at Harper Archer.",
 "Man, practice ran long today. Coach is killing us.",
 "Have you been to the skate park yet? It's decent.",
 "We hoop at Adams Park after school. Pull up sometime.",
 "The new Spider-Man game? I've been grinding all week.",
 "You play 2K? I'm nice with the Hawks, no cap.",
 "Madden with the Falcons — we rebuilding, but it's fun.",
 "Have you been to a Braves game? Truist Park is electric.",
 "I wanna catch Atlanta United live one day. The tifo looks crazy.",
 "The aquarium field trip was actually fire, not gonna lie.",
 "Zoo Atlanta with the school — the lions were active that day.",
 "Have you walked the BeltLine? Me and my boys bike it.",
 "Centennial Park after school — everybody be out there.",
 "The Chick-fil-A on Cascade — that's the after-school spot.",
 "You tried the lemon pepper wings from J.R. Crickets? Elite.",
 "American Deli wings hit different after practice.",
 "MARTA to Five Points then walk to the park — easy day.",
 "The train to the airport just to ride it — we've all done it.",
 "My mom says stay off 285 on foot. Obviously.",
 "Have you seen the new sneakers at the mall? I need those.",
 "Six Flags over Georgia — the Goliath is still the best ride.",
 "White Water in the summer — that's the move.",
 "Stone Mountain laser show with the family — classic.",
 "The High Museum has student days. Art's actually kind of cool."
];
/* TALK_LINES — legacy combined pool, kept for the inspector/debug rig.
   The live picker (npcTalkLine) uses the personality pools above. */
var TALK_LINES=TALK_SHARED.concat(TALK_MAN,TALK_WOMAN,TALK_BOY16);
var TALK_R=4.5;        // TALK prompt range (units) — matches ENTER CAR's 4.5u
var TALK_FACE_R=8;     // NPC turns to face the player inside this range
var TALK_END_R=6;      // conversation auto-ends beyond this range
var talkNPC=null;      // NPC currently in conversation (data object or null)
var talkLastIdx=-1;    // index of the last line spoken — never repeat twice in a row
/* npcTalkLine(n) — picks a random line for NPC n from its personality pool
   (TALK_MAN / TALK_WOMAN / TALK_BOY16) merged with TALK_SHARED — never the
   same pool+index twice in a row (talkLastKey tracks "pool:index"). Falls
   back to the combined TALK_LINES if the NPC type is unreadable. The guard
   loop caps at 10 tries; pools are 70+ lines each, so a repeat is only
   possible on pathological RNG. */
var talkLastKey='';
function npcTalkPool(n){
  /* type: 0=man, 1=woman, 2=boy16 (see TYPE_NAMES). Unknown -> shared only. */
  try{
    if (n && n.type===0) return {name:'man',  lines:TALK_MAN.concat(TALK_SHARED)};
    if (n && n.type===1) return {name:'woman',lines:TALK_WOMAN.concat(TALK_SHARED)};
    if (n && n.type===2) return {name:'boy',  lines:TALK_BOY16.concat(TALK_SHARED)};
  }catch(e){}
  return {name:'all', lines:TALK_LINES};
}
function npcTalkLine(n){
  var pool=npcTalkPool(n), i, guard=0, key;
  do {
    i=(Math.random()*pool.lines.length)|0; guard++;
    key=pool.name+':'+i;
  } while (key===talkLastKey && guard<10);
  talkLastKey=key;
  return pool.lines[i];
}
/* npcDisplayName(n) — the speaker label shown in the dialogue panel.
   Kept generic per Joshua's spec (no named characters yet). */
function npcDisplayName(n){
  try{ return n.type===2 ? 'LOCAL TEEN' : 'ATLANTA LOCAL'; }catch(e){ return 'ATLANTA LOCAL'; }
}
/* npcTalkEligible() — true only when the player is on foot and outside.
   No TALK prompt while driving, inside a building, or riding transit.
   All reads are guarded: a missing global degrades to "not eligible". */
function npcTalkEligible(){
  try{
    if (typeof car!=='undefined' && car && car.driving) return false;
    if (typeof player!=='undefined' && player &&
        (player.inside || player.ridingTrain || player.ridingBus)) return false;
  }catch(e){}
  return true;
}
/* npcTalkNearest(px,pz) — nearest VISIBLE (slotted) NPC within TALK_R of
   (px,pz), or null. Only slotted NPCs have bodies on screen, so the player
   can only meaningfully talk to those. Called every frame from the game's
   updateActionButton() — the slotted scan is tiny (<=40), never the full
   population. */
function npcTalkNearest(px,pz){
  if (!npcReady || !npcTalkEligible()) return null;
  var best=null, bd=TALK_R*TALK_R;
  try{
    for (var s=0;s<MAX_VISIBLE;s++){
      var n=slots[s]; if(!n) continue;
      var dx=px-n.x, dz=pz-n.z, d2=dx*dx+dz*dz;
      if (d2<bd){ bd=d2; best=n; }
    }
  }catch(e){ return null; }
  return best;
}
/* npcFaceTick(dt,px,pz) — runs inside updateNPCs each frame. Every NPC
   within TALK_FACE_R eases its heading toward the player ("turns to the
   individual", Joshua's words) and gets n.focus=true, which pauses its
   wander AI (see aiNPC). Leaving the radius clears focus and AI resumes.
   Also ends the active conversation if the player walks beyond TALK_END_R. */
function npcFaceTick(dt,px,pz){
  if (!npcReady) return;
  var eligible=npcTalkEligible();
  var FR2=TALK_FACE_R*TALK_FACE_R;
  try{
    for (var i=0;i<npcs.length;i++){
      var n=npcs[i];
      var dx=px-n.x, dz=pz-n.z, d2=dx*dx+dz*dz;
      if (eligible && d2<FR2){
        var want=Math.atan2(dx,dz);   // heading convention: 0 = +z (see aiNPC)
        var diff=want-n.heading;
        while (diff>Math.PI) diff-=Math.PI*2;
        while (diff<-Math.PI) diff+=Math.PI*2;
        n.heading+=diff*Math.min(1,10*dt);   // quick ease, no snap
        n.focus=true;
      } else if (n.focus){ n.focus=false; }
    }
    if (talkNPC){
      var tx=px-talkNPC.x, tz=pz-talkNPC.z;
      if (tx*tx+tz*tz > TALK_END_R*TALK_END_R){
        talkNPC.focus=false; talkNPC=null;
        try{ if (typeof hideNpcDialog==='function') hideNpcDialog(); }catch(e){}
      }
    }
  }catch(e){}
}
/* npcStartTalk(n) — begins (or continues) a conversation with NPC n.
   Locks focus so the NPC keeps facing the player while the panel is open.
   Tapping TALK again mid-conversation just serves a fresh line. */
function npcStartTalk(n){
  if (!n) return;
  try{
    talkNPC=n; n.focus=true;
    var line=npcTalkLine(n);
    if (typeof showNpcDialog==='function') showNpcDialog(npcDisplayName(n), line);
  }catch(e){}
}
/* npcEndTalk() — closes the conversation from the NPC side (panel close
   button calls hideNpcDialog directly; this clears the module state). */
function npcEndTalk(){
  try{ if (talkNPC) talkNPC.focus=false; }catch(e){}
  talkNPC=null;
}
window.npcTalkNearest=npcTalkNearest;
window.npcStartTalk=npcStartTalk;
window.npcEndTalk=npcEndTalk;
window.NPC_TALK_LINES=TALK_LINES;   // inspector/debug visibility

/* ---------------- main-loop entry ---------------- */
/* updateNPCs(dt, playerPos) — frame tick (wired by the build agent into
   animate()): AI for all 1000 NPCs always runs (data-only), slots refresh
   every 0.5s, bodies render, Report publishes every 5s. When the player is
   driving, the streaming center follows the CAR, not the player on foot.
   dt clamped to 50ms. Never throws. */
function updateNPCs(dt, playerPos){
  if (!npcReady) return;
  try{
    dt=Math.min(0.05, dt||0.016);
    npcTick++;
    var px, pz;
    if (playerPos && isFinite(playerPos.x)){ px=playerPos.x; pz=playerPos.z; }
    else if (typeof player!=='undefined' && player){ px=player.x; pz=player.z; }
    else return;
    try{ if (typeof car!=='undefined' && car && car.driving){ px=car.x; pz=car.z; } }catch(e){}
    var i;
    try{ npcFaceTick(dt,px,pz); }catch(e){}   // v1.14: NPCs turn to face a nearby player
    for (i=0;i<npcs.length;i++) aiNPC(npcs[i],dt);   // data-only, always runs
    streamT-=dt;
    if (streamT<=0){ streamT=0.5; refreshSlots(px,pz); }
    renderNPCs(dt,px,pz);
    repT-=dt;
    if (repT<=0){ repT=5; publishReport(); }
  }catch(e){}
}
window.updateNPCs=updateNPCs;
/* debug handle for the inspector rig: window.NPC_DEBUG.npcs / .glitches */
window.NPC_DEBUG={ get npcs(){return npcs;}, get glitches(){return glitchLog;} };

tryInit();
})();
